### PR TITLE
Ticket 1257 vesicle product

### PR DESCRIPTION
**Pull request by pkienzle**
The vesicle volfraction problem ([ticket 1257](http://trac.sasview.org/ticket/1257)]) should now be resolved.

I cleaned up product model code, and added much more internal documentation.  Some of the comments about the special parameters at the beginning may be useful to include in the user documentation.

I tested against vesicle against core-shell sphere using random parameter sets and no polydispersity:
```sh
$ sascomp core_shell_sphere@hardsphere,vesicle@hardsphere -pars sld_core=sld_solvent sld=sld_shell volfraction="0.2,(1-radius**3/(radius+thickness)**3)*0.2" -double structure_factor_mode=0 -sets=10 radius_effective_mode="radius_effective_mode-(radius_effective_mode>1)"
```

Testing with polydispersity I get different answers. This is presumably because the average form volume / average shell volume does not match the average of (form volume / shell volume).  Not sure there is anything we can do about this, or which is the "correct" answer.  If this is a problem, put it in a new ticket.
```sh
$ sascomp core_shell_sphere@hardsphere,vesicle@hardsphere -pars sld_core=sld_solvent sld=sld_shell volfraction="0.2,(1-radius**3/(radius+thickness)**3)*0.2" -double thickness=10 radius=100 radius_pd=0.2
```

Scaling F in vesicle by sqrt(volfraction) is a little sketchy: it works out with beta to be equivalent to multiplying it at the end.  The theoretical justification for tying volfraction to "F"-ness when it is really part of the number density calculation is not obvious.

In order to match vesicle to core-shell-sphere in product I had to assume that the volfraction in the P model was sufficient to put it on an absolute scale, and there was no need to scale by volfraction again when computing P@S.  This means that core-shell sphere needs a scale factor to match vesicle when there is no structure factor, but scale becomes 1 when there is a structure factor.  This oddity will go away if we had volfraction to all relevant models ([ticket 475](http://trac.sasview.org/ticket/475)).

### CODE REVIEW

**Comment by pkienzle** [comment]
Steve, please read the extended description at the top of sasmodels/product.py and see if any of it belongs in the user documentation.  I did write it for the maintainer so it does include too much implementation detail for the user, but some of the high level stuff about the use and meaning of the various special parameters might be useful.

The other reason I included you was for a comment on the handling of volfraction, and whether it is clear from our user documentation on structure factors that scale=1 for P@S models.  Taking a look now...   ...and apparently there are no docs for P@S models! Maybe move up the priority on [ticket 1122](http://trac.sasview.org/ticket/1122)?

**Comment by pkienzle** [comment]
> So far have found that running this branch of sasmodels:
> If I fix volfraction to say 0.1 and adjust scale in a fit then an error values appears on volfraction at 0.1* error on scale. Are we really backtracking errors on constrained parameters?

I'm assuming you were fitting both scale and volfraction?

To the extent that constraints are built into the model, then the uncertainties will take the constraints into account.  Perhaps poorly---the diagonal of the covariance matrix doesn't represent correlated errors well---but dream should treat them fine.

> Adding an S(Q) to vesicle, the gui is getting confused and puts the drop down for Reff choice in the lines for S(Q) instead on at the top underneath scale. Suspect volfraction is being used as a flag elsewhere? (I checked that this is a new issue specific to this branch.)

4.x GUI has no drop-downs, so no problem here. This needs to be a 5.0 ticket.

> The expended note in the .py files are very welcome and will greatly help future maintenance. As for the details of the python I am not qualified to comment!

It is icky code.  I'm not sure anyone wants to look at it and understand it.  Ask around if anyone wants to take a look, otherwise approve it once you agree it produces the correct result.

BTW, does the 5.0 GUI do anything with the 'effective_radius' value returned from product model?  If not, we should change it to 'radius_effective'.  The student who worked on the GUI side of beta approximation last summer would be able to answer this question.

**Comment by RichardHeenan** [comment]
So far have found that running this branch of sasmodels:
If I fix volfraction to say 0.1 and adjust scale in a fit then an error values appears on volfraction at 0.1* error on scale. Are we really backtracking errors on constrained parameters?
I'm assuming you were fitting both scale and volfraction?
>> No, of course not, that would be silly, and does give large error values on both.

To the extent that constraints are built into the model, then the uncertainties will take the constraints into account. Perhaps poorly---the diagonal of the covariance matrix doesn't represent correlated errors well---but dream should treat them fine.

Adding an S(Q) to vesicle, the gui is getting confused and puts the drop down for Reff choice in the lines for S(Q) instead on at the top underneath scale. Suspect volfraction is being used as a flag elsewhere? (I checked that this is a new issue specific to this branch.)

4.x GUI has no drop-downs, so no problem here. This needs to be a 5.0 ticket.
>> Thought this branch would only work in v5, do new unit test formats simply get ignored in v4 ? Its the changes here that have broken v5 gui.

The expended note in the .py files are very welcome and will greatly help future maintenance. As for the details of the python I am not qualified to comment!

It is icky code. I'm not sure anyone wants to look at it and understand it. Ask around if anyone wants to take a look, otherwise approve it once you agree it produces the correct result.

BTW, does the 5.0 GUI do anything with the 'effective_radius' value returned from product model? If not, we should change it to 'radius_effective'. The student who worked on the GUI side of beta approximation last summer would be able to answer this question.
>> see email earlier, which said -  Sasview is using effective_radius one place in FittingWidget and three in MultiplicationModel
Piotr is happy to change FittingWidget (though it would be simple enough for anyone to do this) and says MultiplicationModel is not his responsibility (though again anyone could do this). 

How do we sort this simultaneously between sasview and product.py in sasmodels  so that everything still works?

**Comment by smk78** [comment]
Re  ticket 1122:
I have started a new help page /sasview/src/sas/sasgui/perspectives/fitting/media/fitting_sq.rst

Eventually it could be subsumed in to fitting_help.rst, I suppose, but whilst we develop it this seemed the cleaner option.

**Comment by pkienzle** [comment]
I have non-gui docs in sasmodels/doc/guide.   Things in this directory tree get copied into the fitting perspective documentation directory for doc build and can be linked from perspectives/fitting/media/fitting.rst.

**Comment by pkienzle** [comment]
Richard,

(1) volfraction increases the structure factor peak but scale doesn't, so fitting them both is not out of the question.

(2) Don't know what you are referring to re: unit test formats.  I don't see a branch of sasmodels with a different testing framework.  I don't know how many sasmodels tests might be in the ESS gui branches.

(3) Not sure what was changed that would break the 5.0 GUI.  Let me know if there is anything to revert.

(4) MultiplicationModel can be ignored; it is there for backward compatibility with saved 3.x models, and so we don't want to change the names.

(5) I will publish both effective_radius and radius_effective.  The FittingWidget can try retrieving radius_effective, and fallback to effective_radius.  After the next release of both packages, both can remove the cruft.

**Comment by smk78** [comment]
Have moved /sasview/src/sas/sasgui/perspectives/fitting/media/fitting_sq.rst to /sasmodels/doc/guide/fitting_sq.rst as requested, and linked it from /sasview/src/sas/sasgui/perspectives/fitting/media/fitting_help.rst as well as in the fitting documentation index /sasview/src/sas/sasgui/perspectives/fitting/media/fitting.rst

**Comment by smk78** [comment]
Nice work on your additions to fitting_sq.rst, Paul. I have furtled them a bit, in particular: removing the screen shot (more on that in a mo), and reversing the order (I put your "theory" after the parameter descriptions because I thought a) that was more useful, and b) it wouldn't scare the **** out of the reader quite so quickly!).
The screenshot is now in fitting_help.rst, augmented by additional screenshots after Richard had pointed out to me the subtlety of the different ways of generating product models :-) . So I have also expanded this section of fitting_help as well.

**Comment by smk78** [comment]
Changed doc link from _Product_Models to _Interaction_Models in fitting_sq.rst. Will make corresponding change in fitting_help.rst in sasview master.

**Comment by RichardHeenan** [comment]
I think that this PR needs some (possibly simultaneous) changes to the 5.0 gui to allow vesicle x S(Q) to work, see note above which said:

Adding an S(Q) to vesicle, the gui is getting confused and puts the drop down for Reff choice in the lines for S(Q) instead on at the top underneath scale. Suspect volfraction is being used as a flag elsewhere? (I checked that this is a new issue specific to this branch.)

Hence suggest that Piotr take a look please.

**Comment by butlerpd** [comment]
At today's call it was suggested this could now be merged.  Having read carefully through the comments I believe that:
1. the normalization is indeed probably wrong but at a second order effect and will need some discussion/math to come to agreement --> punt to 5.1/4.3 but maybe with a high priority - make a new issue
2.  Lat comment from Richard who is the person putting the block on the merge is that the GUI is still being confused.  If truly a GUI issue this could be merged but since the plan is to merge this and the GUI side together probably doesn't hurt to check.  Will ask Richard to approve first

**Comment by butlerpd** [comment]
At The April 30 conf call it was suggested that this PR could be merged.  Given that it remained blocked by comments from @RichardHeenan who was not present and the lengthy comments section it was agreed that @butlerpd would review all those to ascertain if there was in fact anything that looked outstanding. 

In that review two issues emerged:
1. I believe that @pkienzle comment at the very beginning about polydispersity is indeed a problem. It will require some discussion and thinking but I believe to be correct the averaging needs to be done differently.  This however is a second order correction mostly and cannot be resolved in short order so as @pkienzle suggests I will generate a **new ticket for 5.1/4.3**
2. the last comment from @RichardHeenan  still indicates some problem with the software getting "confused" though not clear whether entirely a GUI issue or something to do with this request.  For this I would like a confirmation from @RichardHeenan of the current status and his permission to merge.

**Comment by RichardHeenan** [comment]
Initial testing of merged code, show that vesicle with S(Q), thougg much better than before, is not working properly. The volfraction_effective being used by the S(Q) is way too large, the radius_effective is correct.

In my test case the 5% shell volume, became 7.63% total volume, but fitting back the S(Q) generated by sasview showed it was using 30.523% vol.

Will see if I can work out further what is going on.

**Comment by pkienzle** [comment]
You could uncomment the following to show the R_e and Phi_e used by S(Q):
https://github.com/SasView/sasmodels/blob/e3ec98f8af61249f5b64dd4f2060e1881530af3a/sasmodels/product.py#L523

Using 5% volume fraction and comparing to solid core shell sphere I see substantially the same result though in this case with a 6.5% "correction" because the average of the volume ratio is not the same as the ratio of average volumes:
```sh
$ PYOPENCL_NO_CACHE=1 sascomp vesicle@hardsphere,core_shell_sphere@hardsphere -double -pars sld_core=sld_solvent sld_shell=sld volfraction="0.05,volfraction/(1-radius**3/(radius+thickness)**3)*1.065" thickness=5 radius=100 radius_pd=0.2
```

Looking at what happens with a more realistic distribution of vesicle sizes (e.g., from [1]), which  I approximated by a lognormal with radius 45 and width 0.5, gives:
```sh
$ PYOPENCL_NO_CACHE=1 sascomp vesicle@hardsphere,core_shell_sphere@hardsphere -double -pars sld_core=sld_solvent sld_shell=sld volfraction="0.05,volfraction/(1-radius**3/(radius+thickness)**3)" thickness=10 radius=45 radius_pd=0.5 radius_pd_nsigma=6 radius_pd_n=80 radius_pd_type=lognormal -weights -midq
...
Vesicle: 60.56524403835097 0.16237098587594384
CS sphere: 60.56524403835097 0.11054817275747508
...
```
The effective volume fraction is different by 50%.  If I "correct" it by using the vesicle volume fraction in the CS sphere interaction model, then the results are the same to 14 digits.

[1] Hallett, F.R., Watton, J., Krygsman, P., 1991. Number distributions by dynamic light scattering. Biophys. J 59, 357--362. https://doi.org/10.1016/S0006-3495(91)82229-9

**Comment by RichardHeenan** [comment]
Have also just tried a hollow_cylinder times hard sphere, though the volume fraction displayed in 5.0 is 10%, in this particular case the S(Q) is for 18% and hence the fit is not quite the same as from 4.2, so something is not right.

**Comment by RichardHeenan** [comment]
Back to vesicle times hard_sphere, adding the diagnostic print as suggested by Paul above shows that S(Q) is picking up the **default** volume fraction in S(Q) of 0.2 instead of the user input 0.05, multipying that by the correct volume ratio to get a stupidly large volume fraction in S(Q).

Paul K - could you investigate further please, as I need to go home now.

**Comment by pkienzle** [comment]
Just pulled sasview/ess_gui and sasmodels/master.  

Uncommenting the print statement, then selecting vesicle@hardsphere gives the following:
```
Vf=0.2  Reff, Veff 130.0 0.36708438308067687
Vf=0.05  Reff, Veff 130.0 0.09177109577016922
```
Turing on polydispersity:
```
Vf=0.05  Reff, Veff 130.00000000000003 0.09268391695957491
```

So it seems to be behaving as intended, at least on my mac.

Still need to figure out the correct relationship between the solid and hollow shapes.

**Comment by butlerpd** [comment]
Without doing the calculation those numbers look roughly right ... was is the thickness of the shell?

**Comment by pkienzle** [comment]
Default values, so 100 core, 30 shell.

**Comment by RichardHeenan** [comment]
Aaagh -apologies, I had a sudden realisation this evening that I was in the wrong branch of sasmodels.
Checking again now, I have both vesicle times hard_sphere and hollow_cylinder time hard_sphere working correctly.
We will have to do some work on the hollow_cylinder case as noted above, since the volfraction appears in the S(Q) part of the parameter table but is actually the shell volume, not the value for total volume that is actually being used in S(Q), which s going to confuse people. 
(I am by the way testing with AOT micromeulsion shell contrast, which fits to Rcore ~23, shelll thicknes ~8 ang, total vol frac ~ 5%, so is very sensitive to getting things wrong.)

**Comment by butlerpd** [comment]
LOL ... too many branches in too many repos :-)

And indeed, looking at @pkienzle's results, checking our docs R is the inner radius which means that the real_vol_frac/eff_vol_frac = 1-[R<sup>3</sup>/(R+t)<sup>3</sup>] or in this case 1.8354....  so 0.2 lipid fraction does indeed yield 0.3671 interaction volume fraction (note that from the above, the same real lipid (surfactant) vol fraction will lead to different interaction fractions depending on the radius which might change with Temp for example while the "real" vol fraction cannot change as it is an invariable property of the (sealed) sample.

**Pull request merged**
