### PR TITLE
Ticket 1156: rename dnn to lattice spacing for paracrystalline models

### PR DESCRIPTION
**Pull request by pkienzle**
See Ticket [#1156](http://trac.sasview.org/ticket/1156).

This code updates the name of the dnn parameter for lattice spacing.  There are lots of questions about whether the paracrystal parameters are correct.  The real space modeller has been extended to allow some experiments with monte carlo sampling, but this code may not be correct (see [#1156:10](http://trac.sasview.org/ticket/1156#comment:10)).

I'm putting it as a PR so it doesn't get forgotten.  It needs to be checked whether it performs as promised (renaming the parameter) irrespective of when the model itself is correct.  If so, then it should be merged, because there are other tickets on paracrystal correctness ([#805](http://trac.sasview.org/ticket/805), [#975](http://trac.sasview.org/ticket/975), [#1036](http://trac.sasview.org/ticket/1036)).

### CODE REVIEW

**Comment by butlerpd** [comment]
Why is this against the beta branch instead of master?  Not sure I am comfortable with changing the name with all that entails in the support infrastructure for backwards compatibility till we actually are convinced we FULLY understand the model.  I realize there is strong evidence that this is correct BUT I also know form painful experience that sometimes it is the unknown unknowns that bite us and in fact we may be completely misunderstanding everything.

**Comment by pkienzle** [comment]
I rebased this branch on PR #382, and fixed some errors in the lattice calculations.

Running the following:
```sh
python explore/realspace.py --qmax=1 --mesh=400 --type=sc --shuffle=0.03 \
    --lattice=40,40,40 --spacing=2,2,2 --samples=150000 sphere radius=25
```
eventually gives:

image

so at least for simple cubic the peak positions and heights are consistent with the corresponding *lattice_spacing* variable in the revised model.  Similarly bcc and fcc give the main peaks, though they don't match the fine structure very well:

image

Some of this may be explained by finite lattice size (equivalent to low pass filtering) but it could also be due to errors in the simulation code or the analytic function.

I don't simulate paracrystals, only crystals with thermal distortion, so I'm not able to check that the *lattice_distortion* parameter is consistent.

**Comment by pkienzle** [comment]
Check results against other software, such as scatter.[1]

[1] Förster, S., Apostol, L., Bras, W., 2010. Scatter: software for the analysis of nano- and mesoscale small-angle scattering. Journal of Applied Crystallography 43, 639–646. https://doi.org/10.1107/S0021889810008289

**Review by butlerpd — CHANGES_REQUESTED** [review]
As discussed in #284 (was trac#1156), this is not the correct fix. Once the maths from the paper are implemented correctly it would be interesting to run these tests again but given the age of this PR (particularly are far behind main it is at this point) and the fact that the needed corrections are much simpler  as thy only require changing a few lines of code in 2 files, I recommend we close this PR without merging

**Comment by butlerpd** [comment]
Paul to check with @pkienzle before closing and deleting branch

**Comment by pkienzle** [comment]
This PR is primarily about renaming the `dnn` to `lattice_spacing` and `d_factor` to `lattice_distortion`, which still seems like a reasonable request.

The only math change I see is a √1/2} scaling on fcc and √3/4} on bcc when computing radius for volume fraction.

**Comment by butlerpd** [comment]
As discussed at the fortnightly call, this PR makes (incorrect) changes to the modes as well as changes to the simulation code only used for testing purposes so far.  Thus I am only closing the PR but not the branch as @pkienzle wants to ensure that the simulation gets updated appropriately.

**Note**: the #284 discussion (dated Feb 25, 2022) points out the code in fact does need changing. simply replacing `dnn` with `lattice_spacing` will also be incorrect.  In fact, both are used in the math, but the code only uses `dnn`. `dnn` is correct most of the time. However there is a single equation where `dnn` is used in the code which should in fact be `lattice_spacing`.

**Comment by pkienzle** [comment]
Simulation code is in #507 so I'm deleting the branch.

**Pull request closed without merging**
