### PR TITLE
FIX: move shell_volume to P scaling in P@S

### PR DESCRIPTION
**Pull request by pkienzle**
Addreses https://github.com/SasView/sasview/issues/1698

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on OSX

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on Win

**Comment by RichardHeenan** [comment]
Have briefly tested the first windows build from this PR. The P(Q) saved in the data explorer is now correctly scaled and I am happy.  
BEWARE the scaling is NOT the same as in v4, as now "scale" is included inside the saved P(Q), this is good as appending the P(Q) to a plot gives what users might expect to see, a line that overlaps the fit when S(Q) goes to unity at higher Q (except without the flat background which is not included), regardless of the value of "scale".

Addresses  https://github.com/SasView/sasview/issues/1698

**Comment by butlerpd** [comment]
Do we need to change documentation. Create ticket then merge this

**Comment by RichardHeenan** [comment]
Yes, could merge this and also create a ticket for the doc change.

**Comment by smk78** [comment]
Errrr... I just pulled on main to test this but was surprised it didn't appear. But I just noticed that this merged into master! So now I'm totally confused. I thought we were fixing 5x. Was that not the case? @RichardHeenan does say above _'BEWARE the scaling is NOT the same as in v4'_. Should this have merged into main?

**Comment by smk78** [comment]
Ohhh... its sasmodels. Ignore me! :-)

**Pull request merged**
