### PR TITLE
TST: github actions test

### PR DESCRIPTION
**Pull request by andyfaff**
This PR makes the test surface for `sasmodels` larger. Examining the matrix of Ubuntu/macOS/Windows + Python 3.6/3.7/3.8.

### CODE REVIEW

**Comment by andyfaff** [comment]
You can see the GH actions CI run at https://github.com/andyfaff/sasmodels/actions, which will appear for this repo when merged.

**Comment by andyfaff** [comment]
(might need the repo settings tweaked as well to activate it).

**Comment by andyfaff** [comment]
Also reenabled pyopencl testing on travis. If pyopencl is going to be the default mode of calculation then it should be in CI.

**Comment by pkienzle** [comment]
If you pull #409 into this branch it will show the name of the model being tested and a tag such as `[dll]` or `[opencl]`.  This will help verify that the OpenCL tests are running.

I briefly looked into running cuda tests as well on travis, but didn't find anything conclusive.

**Comment by andyfaff** [comment]
I think they are running on Travis (I used an assert), but it'd be good to have that functionality.
Turns out that it's difficult to get pyopencl/opencl installed if you're not using conda.

**Comment by andyfaff** [comment]
The github actions setup is now running the pyopencl tests (3.6/3.7/3.8) on macOS and Ubuntu.

**Comment by andyfaff** [comment]
closing, because I'm experimenting with windows CI offline. Will reopen once investigations finish

**Comment by andyfaff** [comment]
https://github.com/andyfaff/sasmodels/runs/767679437?check_suite_focus=true shows that pyopencl is now being tested successfully on macOS/Linux/Windows across 3.6/3.7/3.8

**Comment by pkienzle** [comment]
1. Would this replace the travis-ci and appveyor dependencies?  If so, the .travis.yml and appveyor.yml files can be dropped.

2. What's the response time like for the various platforms?  Some of the appveyor builds are slow to appear, so dropping that would be good.

3. How do you administer the workflow, such as following the build as it is happening and cancelling it before the entire grid is run so that you can go onto the next build?

4. Py27 support is needed for a little while yet.

5. Checking all python versions on linux and checking only the sasview python version on mac and windows should suffice.  Just 'cuz the commons are available doesn't mean when shouldn't treat them gently.  Similarly, does it automatically abort a build when a new commit comes in (unlike travis)?

6. Need to update the badges in README.rst.

**Comment by andyfaff** [comment]
> Would this replace the travis-ci and appveyor dependencies? If so, the .travis.yml and appveyor.yml files can be dropped.

The travis CI run also builds the documentation (which this GH action doesn't do at the moment), has a slack notification, does some kind of deployment to danse.chem.utk.edu on successful completion, and tests the package within a conda environment.
Appveyor also does its tests within a conda environment. This PR does everything in a 'normal' Python environment with all dependencies installed using pip. On windows pyopencl is installed from www.silx.org because there is no easily available wheel elsewhere.

Keeping some tests within a conda environment is probably worth it if a sizeable fraction of end users are going to be within that kind of python environment (although a conda-forge feedstock build would also test that).
The Python versions on appveyor are at the older end of the spectrum; 2.7 and 3.5 which numpy doesn't support anymore.

> What's the response time like for the various platforms? Some of the appveyor builds are slow to appear, so dropping that would be good.

I've been using GH actions for a while and they start up immediately. The longest matrix entry to complete is on windows because the `choco install opencl-intel-cpu-runtime` takes a while to complete. It may be possible to cache that package for a quicker run time. The total runtime of the CI is ~8mins.

> How do you administer the workflow, such as following the build as it is happening and cancelling it before the entire grid is run so that you can go onto the next build?
Similarly, does it automatically abort a build when a new commit comes in (unlike travis)?

The workflow is on an actions tab in the repository, https://github.com/andyfaff/sasmodels/actions. The ellipsis on the RHS allows you to manually cancel the run before it finishes. You can also have fail-fast. I don't know about automatic cancelling of previous pushes, but there is an [action](https://github.com/styfle/cancel-workflow-action) for that.

> Checking all python versions on linux and checking only the sasview python version on mac and windows should suffice. Just 'cuz the commons are available doesn't mean when shouldn't treat them gently.

I don't think the workload will be high, but one can do the checks you suggest. I've also been using GH actions to build + test wheel matrices (Linux/macOS/windows) and pyinstaller'd standalone programs (c.f. SasView), followed by an artefact upload. This goes pretty much all the way towards full automation of a release process (and you can take that final step if required).

**Comment by andyfaff** [comment]
GH actions also run the jobs with good parallelisation, and complete much faster than appveyor.

**Comment by pkienzle** [comment]
@andyfaff, do you have any experience using lint with workflows?

sasmodels is still far from lint-free (even after #412) so it can't be a build error, but it would still be useful to track which new lint complaints are introduced by a PR.

We used to build and run lint on Jenkins, but Jenkins stopped building sasmodels a while ago.

**Comment by andyfaff** [comment]
I assume you have the lint command.
Linting could happen before or after testing.
If you run it afterwards you could run the tests, but make it fail on the lint step.
What do you want to happen if the lint fails?

**Comment by andyfaff** [comment]
Personally I'd prefer to have a hard stop if the lint fails, because the code then keeps its 'PEP8' ness. People then adapt their coding practices accordingly.

**Comment by pkienzle** [comment]
Agreed somewhat.  Maybe run lint on the branch and on the base of the PR and show the difference?

PEP8 was never meant to be prescriptive.  Making code ugly so that it passes recommended practices designed to make code more readable is counterproductive.

However, lint is only useful if it flags potential errors. If these are hidden within a bunch of known harmless warnings reviewers aren't going to see them. Ideally I would like to flag each new lint warning introduced by a PR so the reviewer can decide whether it is an acceptable readability tradeoff.  

Some examples of warnings that I don't want to disable, but I don't want to want to enforce:
* *unused-variable*, for example in `counts, edges = histogram(data)` when you don't care about `edges` but still want to let the reader know that it is there,
* *unused-argument,* for example in a method where a subclass can't do anything with the argument but the caller will still pass it in,
* *global-statement*, so you can make lightweight singletons as part of a module,
* *invalid-name*, so that the variables in the code match the variables in the equation,
* *too-many-branches*/*too-many-return-statements*, except that python lacks a switch so sometimes you want to have too many
* *using-constant-test*, except as a way of commenting out code blocks 

Cluttering code with `# pylint disable=...` line noise to hide these warnings isn't terribly appealing.

**Comment by andyfaff** [comment]
https://github.com/scipy/scipy/commit/d806cd1936d59159bfa1890865acab2f7c7d2a39 ?

**Comment by pkienzle** [comment]
Interesting...  I see that it is looking directly at the diff, so I don't know how it can do more in-depth analysis such as unused parameter checks.

For finding the common ancestor the code could use `git merge-base`.  For example:
```sh
$ git merge-base ESS_GUI master
5582b078dce28d6d3003549e906ce92e0270639d
```

I suppose we could run pylint and save the output, switch to the common ancestor and run pylint again, then show a diff on the output.  Somehow making that diff visible to the PR reviewer?

**Comment by andyfaff** [comment]
Is this mergeable? Or does it need changes?

**Comment by pkienzle** [comment]
We need a discussion on which CI facility or facilities we are going to use.  I would rather not add one (github actionsw) without dropping one or two (jenkins, travis, appveyor). Then the question is how to get there, since, as you point out this doesn't not yet reproduce what we do on travis and jenkins.  Adding these capabilities in additional PRs is reasonable assuming we agree that's the direction we want to go.

A topic for the next fortnightly meeting?

BTW, I was confused by the "TST:" tag, thinking that this was an experiment rather than a PR that was ready to merge. Now I see that the label is part of the scipy [editing workflow](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#in-more-detail) indicating a change to tests.

A "BLD:" or "DEV:" tag would be more appropriate since it doesn't actually change any tests, but does change the build system/development tools.

**Comment by andyfaff** [comment]
>  I would rather not add one (github actionsw) without dropping one or two (jenkins, travis, appveyor)

I can understand that. However, I have been bitten in the past by not having a comprehensive enough test surface. At the moment this GH action examines what would happen with a pip installed environment. Whereas travis/appveyor are testing out a conda approach, I can't speak for Jenkins. At the moment only travis is really usable for `ppc64` and `aarch64`. It's a simple upgrade path for the GH action to also make a wheel and make it/them available as artefacts. This may make a release easier. However, `sasmodels` doesn't have any compiled code, so that may not be relevant.

I probably won't be able to make a fortnightly meeting.

**Comment by pkienzle** [comment]
This was against master, not ESS_GUI. Need a new PR for ESS_GUI.

**Comment by krzywon** [comment]
Is there an ESS_GUI branch in sasmodels?

**Comment by pkienzle** [comment]
... nevermind.  Sasview was the group, not the repo name.

**Comment by pkienzle** [comment]
The opencl tests are not running on windows. I put in ticket #425 since this PR is already merged.

**Pull request merged**
