### PR TITLE
WebGL jitter viewer

### PR DESCRIPTION
**Pull request by pkienzle**
Better rendering of jitter viewer, using webgl inside a jupyter notebook.

Not yet a standalone solution that can be put into the docs since it uses a python server to generate the scene.  Also, the response time for resetting the plot after each scene change is too slow.  However, it does do a better job of rendering the view.

The existing mplot3d viewer is still the default.  Other than a color change on the parallelepiped, this should not affect sasview.

See [ticket 926](http://trac.sasview.org/ticket/926).

### CODE REVIEW

**Comment by pkienzle** [comment]
Basing this off the py3 branch so that I can resolve the merge conflict early.

**Comment by pkienzle** [comment]
I tested that it works with the existing ">Tools >Orientation Viewer" menu option in sasview master.

**Comment by pkienzle** [comment]
Orientation viewer menu in sasview should pop up a 3-D parallelpiped which you can rotate with sliders.  If it does not, then perhaps it is because you have an old version of matplotlib.  Here is the stackoverflow link:

    https://stackoverflow.com/questions/37661119/python-mpl-toolkits-installation-issue

This PR is mostly concerned with providing support for jitter viewer in jupyter notebook, with much prettier 3D rendering. See comments on top of sasmodels/jitter.py for details on how to set it up.  You will need to pip install ipyvolume in your jupyter environment before it will work.

**Comment by mdoucet** [comment]
OK since this is part of sasmodels I guess that's fine. But we should fix this in SasView. The menu item should not be displayed unless clicking it is going to work. Even when the window does pop up it's a little confusing because of the bottom part, which appears like controls that don't do anything.

**Comment by pkienzle** [comment]
Works for me.  Can you create the appropriate ticket describing the problem?

**Pull request merged**
