### PR TITLE
Update test.yml

### PR DESCRIPTION
**Pull request by wpotrzebowski**
It seems that python 3.6 test is no longer supported for osx. The question is if we should extend for new ver. of python e.g. 3.9

### CODE REVIEW

**Review by pkienzle — APPROVED** [review]

**Comment by pkienzle** [comment]
Don't know why the doc build is failing and breaking our CI. My temptation is to strip any `WARNING.*py:class` from the log before checking.

**Comment by pkienzle** [comment]
In `direct_model.py` type `Kernel` and type `KernelModel` are used in practically the same environment (both imported from `kernel.py` solely for type hinting; both have docstrings in `kernel.py`), yet one causes a sphinx nitpick warning and the other does not. I would rather turn off the broken sphinx nitpick than remove type hints from the code.

Trying with type annotations rather than type in docstrings to see if sphinx can handle it better. This will break python 2.7 compatibility, which we shouldn't care about anymore since 2.7 is no longer supported. A much better solution than removing the type hints, assuming it works.

The tests have now run, and it seems like the type annotation solution will work. Maybe because the symbol is actually used in the file now, whereas it was unused before (with type hints in the comments the interpreter didn't know the symbols were used).

I'm trying something similar for the `Calculator` symbol problem in `compare.py`, but I'll reverse it if it fails the tests.

Are we ready for a complete break from 2.7, preferably to 3.8 so we can use Protocol without installing `typing_extensions`?

**Comment by butlerpd** [comment]
Sad as it makes me, I think trying to maintain python 2.7 compatibility is just getting silly.  We can say the last sasmodels version is the last that will work under 2.7?  it is always available if somebody wants to use it I guess?

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on OSX

**Pull request merged**
