### PR TITLE
Ticket 822 v5 unit tests

### PR DESCRIPTION
**Pull request by pkienzle**
This branch now contains a lot of cleanup code:

- effective_radius => radius_effective everywhere (almost)*
- spaces removed from ends of lines (from merge from master)**
- fixes to the debug infrastructure

Please review and merge quickly before other changes get piled on.

\* the intermediate value for radius_effective is being returned from product model with the key 'effective_radius' since I don't know if the Qt GUI is using it.  If not, please change that as well.

\** Please set your editors to trim lines!  One point added to pylint score for each trailing space!

### CODE REVIEW

**Comment by smk78** [comment]
ready for testing OSX

**Comment by smk78** [comment]
ready for testing OSX

**Comment by RichardHeenan** [comment]
ready for testing on OSX

**Comment by RichardHeenan** [comment]
5.0 ready for testing on Win

**Pull request merged**
