### PR TITLE
generalise broad peak model

### PR DESCRIPTION
**Pull request by dehoni**
The model "broad_peak" can be generalized to cover Lorentz like behavior and Debye-Anderson-Brumberger by introducing a  outer power term with "exponent_p". The commit does the necessary changes.

### CODE REVIEW

**Comment by butlerpd** [comment]
Will this break backward compatibility with old projects?  Does it require some translations for that compatibiltiy?

**Comment by krzywon** [comment]
To keep backward compatibility with old save projects saved with old parameter names you will need to update [sasmodels/conversion_table.py](https://github.com/SasView/sasmodels/blob/master/sasmodels/conversion_table.py). The python file houses a dictionary that maps the previous SasView version to the changes made **after** that version was released. This can accommodate model name and parameter name change.

General usage, but more information is given in the file documentation:

> <old_Sasview_version> : {
<new_model_name> : [
            <old_model_name> ,
            {
                <new_param_name_1> : <old_param_name_1>,
                ...
                <new_param_name_n> : <old_param_name_n>
            }
        ]
    }

**Comment by krzywon** [comment]
More information: https://www.sasview.org/docs/dev/sasmodels-dev/overview.html#model-conversion

**Comment by dehoni** [comment]
Tested to save a project and analysis after fitting with some test data from the PR and load it to the Release version, and vice versa. The parameters are passed on correctly and files are read smoothly.

**Review by krzywon — APPROVED** [review]
The documentation and mathematics in the code match each other, and the conversion table update matches what is expected. The build failure is due to a doc building failure that was fixed in #462. There is an issue in SasView, noted in [SasView#1902](https://github.com/SasView/sasview/issues/1902) when loading projects with reparameterized models. Whether this PR should be held up because of the SasView issue is up for discussion.

**Comment by butlerpd** [comment]
sasmodels ready for testing on Win

**Comment by butlerpd** [comment]
Made a fit using `broad_peak` fitting the `test/1d/hSDS_D2O_2p0percent.xml` and saved as a project in versions 4.2.2; 5.0.4; 5.0.5a1 main branch build of 13 Oct 2021.  Then installed the sasmodels Jenkins PR build of PR #458.

**Results**
* As expected the json files did not run through the converter.  So the value of any renamed parameters that are different than the default are **NOT** imported.  In other words this break projects using this model created in prior 5.x versions.
* Loading the svs project from 4.2.2 would not load at all and instead through the following error
```
19:22:58 - WARNING: ER(...) function ignored. Using radius_effective(mode, ...) instead if it exists.
19:22:58 - ERROR: Error while reading the project file: No module named 'sas.sascalc.dataloader.readers.cansas_reader_HDF5'
19:22:58 - ERROR: Error while converting the project file: local variable 'datasets' referenced before assignment
```
* Loading the svs project from 5.0.4 release version works as expected
* Loading the svs project from the 5.0.5a1 main branch build of 13Oct produces the same error as above

**Conclusion:**
* This PR breaks previous 5.x projects but not due to the PR itself but due to a bug in the 5.x not running the converter.
* loading 4.x projects have become broken since 5.0.4 but prior to this PR. However that means I cannot check that the conversion is being called here.  This seems like something that must have been broken in one of @krzywon commits on the dataloaders?
* Merging requires more discussion ... or getting the loader fixed.

**Comment by butlerpd** [comment]
I think we agreed that this could be merged to main once the release branch is created? The SasView Issue, [SasView #1902](https://github.com/SasView/sasview/issues/1902), to fix the problem with loading project has already been listed as a blocker.

**Pull request merged**
