### PR TITLE
Move to proper argument parser in model_test

### PR DESCRIPTION
**Pull request by rprospero**
I replaced argv handling in model_test.py with a call to the argparse
library.  The replacement offers the same interface, but uses less
code, is a bit more readable, provides proper help messages, and is
eight lines shorter.

### CODE REVIEW

**Comment by pkienzle** [comment]
This will conflict with the cuda branch.  Can you please base it off the beta_approx branch, and we can pull it into PR #90?   This already includes the cuda stuff.

The selection of engine is currently optional.  If you run without giving the engine as the first argument, then it will run with all engines.  You could do this by adding an engine flag `-e dll`, maybe accepting a list `-e dll,opencl,cuda`  or a set of booleans for each engine `--dll --opencl --cuda` or abstract flags `--cpu --gpu` in case you don't want to specify CUDA vs. OpenCL.

The distinction between "all", "only some" and "all but some" could also be made cleaner.  Triggering off the first model name of "all" is a little unusual.  Maybe an exclude flag `-x` which if set indicates that the list of models on the command line is the list of models to be excluded, not the list of models to be included?  Then the "all" isn't needed, since all is the default.

**Comment by rprospero** [comment]
The PR as submitted was written to match the existing behaviour.  I'll try and implement your suggestions this afternoon, which should be clearer and more concise, but will change the behaviour of the module.

**Comment by pkienzle** [comment]
Don't need to worry that much about consistency with past behaviour: this is a developer tool, not a user tool.  As long as there is a way to run all models or just one model, it should be fine.

Looking at the code again, if the first argument is in `core.KINDS` then the list of models is given by `core.list_models(kind=args[0])`.  This allows us to test different classes: `all, py, c, single, double, opencl, 1d, 2d, magnetic, nonmagnetic`.   So ignore what I said about `-x`.  Easiest to leave this behaviour in place (though better documented), or you could add it as a "kind" option if you want more traditional command line behaviour, and stuff opts.kind on the front of the model list before calling `make_suite()`.

**Comment by pkienzle** [comment]
I adjusted the option parsing so that execution engine is specified with "-e" instead of the first argument.  In the process of testing, I was reminded that you can use 'py', 'single', etc. instead of 'all' when specifying what to test.  This was slightly broken (it didn't allow combinations such as 'py+2d') so I fixed that as well.  I added some docs.  Since this is an internal testing tool, I didn't create a ticket and submit it for review.  You can use `git show -p d92182f88244` to see the changes if you care.

**Pull request merged**
