### PR TITLE
ticket 363: Allow other processes to run during long computations

### PR DESCRIPTION
**Pull request by pkienzle**
Running barbell with 35x35 polydispersity on a 300x300 image no longer leaves the computer completely unusable (Macbook Pro, OS 10.9.5).

Needs to be tested on different operating systems and different graphics cards.  Change to the sasmodels directory, type "git checkout ticket363", then run sasview as usual.

Also, run speed tests on the old and new versions to make sure the GPU protection does not introduce too much of a performance impact:

    sascomp cylinder 20 0 -noplot -mono
    sascomp cylinder 20 0 -noplot radius_pd=0.2 radius_pd_n=35 length_pd=0.2 length_pd_n=35

### CODE REVIEW

**Comment by pkienzle** [comment]
ref ticket #363

**Comment by wpotrzebowski** [comment]
Testing on Intel(R) Iris(TM) Graphics 6100 and OSX 10.11

1) Barbell model works and computer doesn't freeze

2) Speed test
It seems to have no impact on performance. 

From branch ticket 363
../sascomp cylinder 20 0 -noplot -mono
INFO:root:building cylinder-float32 for OpenCL Intel(R) Iris(TM) Graphics 6100
OCL32 t=0.94 ms, intensity=102451
../sascomp cylinder 20 0 -noplot radius_pd=0.2 radius_pd_n=35 length_pd=0.2 length_pd_n=35
INFO:root:building cylinder-float32 for OpenCL Intel(R) Iris(TM) Graphics 6100
OCL32 t=137.17 ms, intensity=125720

From master
../sascomp cylinder 20 0 -noplot -mono
INFO:root:building cylinder-float32 for OpenCL Intel(R) Iris(TM) Graphics 6100
OCL32 t=1.03 ms, intensity=102451
../sascomp cylinder 20 0 -noplot radius_pd=0.2 radius_pd_n=35 length_pd=0.2 length_pd_n=35
INFO:root:building cylinder-float32 for OpenCL Intel(R) Iris(TM) Graphics 6100
OCL32 t=137.77 ms, intensity=125720

**Comment by ajj** [comment]
Testing on Intel IRIS 5100 OSX 10.11.6 

1) Barbell model works and doesn't freeze computer

2) Speed test:

Branch ticket 363:
./sascomp cylinder 20 0 -noplot -mono
INFO:root:building cylinder-float32 for OpenCL Iris
OCL32 t=0.87 ms, intensity=102451

./sascomp cylinder 20 0 -noplot radius_pd=0.2 radius_pd_n=35 length_pd=0.2 length_pd_n=35
INFO:root:building cylinder-float32 for OpenCL Iris
OCL32 t=110.68 ms, intensity=125720

Master:
./sascomp cylinder 20 0 -noplot -mono
INFO:root:building cylinder-float32 for OpenCL Iris
OCL32 t=1.10 ms, intensity=102451

./sascomp cylinder 20 0 -noplot radius_pd=0.2 radius_pd_n=35 length_pd=0.2 length_pd_n=35
INFO:root:building cylinder-float32 for OpenCL Iris
OCL32 t=112.17 ms, intensity=125720

(Will also test on Windows 10 with dual GPUs if I can get pyopencl to compile)

**Comment by pkienzle** [comment]
Testing on Radeon R9 Nano Windows 7

1) Barbell model works and doesn't freeze computer (had to use 1000x1000 to generate any lag)

2) speed is identical for ticket363 and master

**Comment by pkienzle** [comment]
binary wheels are available for windows:

    http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopencl

**Comment by ajj** [comment]
Testing on Windows 10 / Core i7 6700 /  2 x GTX970 (don't know if it is using both)

1) Barbell doesn't freeze

2) Speed tests
    ticket363 : OCL32 t=0.80 ms, intensity=102451 & OCL32 t=46.10 ms, intensity=125720
    master : OCL32 t=0.80 ms, intensity=102451 & OCL32 t=47.65 ms, intensity=125720

**Comment by pkienzle** [comment]
Only using one device.

We would need to set up bumps so that it uses multiple threads, with each
thread targeting a different GPU device, which should allow fits to run
twice as fast.  Using the CPU as a third OpenCL device might be
counterproductive if it is too much slower.

**Pull request merged**
