### PR TITLE
Doc Update: Polydispersity in Sasmodels

### PR DESCRIPTION
**Pull request by smk78**
This PR attempts to address some of the documentation deficiencies in SasView raised in https://github.com/SasView/sasview/issues/1839. It is complemented by PR https://github.com/SasView/sasview/pull/1938.

The usage text regarding the array distribution has been tweaked and clarified.

### CODE REVIEW

**Review by pkienzle — APPROVED** [review]
Text is okay as is.

The *Suggested Applications* suggestion says to use *uniform* for orientation, but you can also use gaussian if 3σ is small enough. Better would be to move *Maier-Saupe* and/or *Cyclic gaussian* from [examples/weights](https://github.com/SasView/sasmodels/tree/master/example/weights) to `sasmodels/weights.py`, or at least mention that they can be added as user-defined distributions (and add them to the marketplace?)

What we call the Boltzmann distribution in `sasmodels/weights.py` is in fact a Laplace distribution. Boltzmann is a limiting case with no shift, no negative values, and scale related to temperature. We could mention in the docs that it is the Laplace distribution, but I don't think we want to change the name in the code. The distribution I put in `example/weights/laplace.py` isn't Laplace since its scale is `b` rather than `1/b`.

**Comment by smk78** [comment]
@pkienzle commented:

> Better would be to move _Maier-Saupe_ and/or _Cyclic gaussian_ from [examples/weights](https://github.com/SasView/sasmodels/tree/master/example/weights) to `sasmodels/weights.py`, or at least mention that they can be added as user-defined distributions (and add them to the marketplace?)

If we put the Maier-Saupe and Cyclic_gaussian distributions on the Marketplace, how would you use them from SasView?

**Comment by pkienzle** [comment]
According to the [docs](https://www.sasview.org/docs/user/qtgui/Perspectives/Fitting/pd/polydispersity.html#user-defined-distributions) you need to save the file into `~/.sasview/weights`.

Note that we probably need to change the way distributions are defined if we implement #486, but I don't expect that to happen any time soon.

**Comment by smk78** [comment]
@pkienzle commented:

> According to the [docs](https://www.sasview.org/docs/user/qtgui/Perspectives/Fitting/pd/polydispersity.html#user-defined-distributions) you need to save the file into `~/.sasview/weights`.

Oops. My bad! I should have read our wonderful docs! Just tested this and it works! Fantastic! The 'plugin' distribution appears in the _Function_ drop-down and can be used like the in-program distributions.

image

I'm just going to push a minor doc edit for the benefit of Windows users though.

**Comment by smk78** [comment]
@pkienzle commented:

> What we call the Boltzmann distribution in `sasmodels/weights.py` is in fact a Laplace distribution. Boltzmann is a limiting case with no shift, no negative values, and scale related to temperature. We could mention in the docs that it is the Laplace distribution, but I don't think we want to change the name in the code. The distribution I put in `example/weights/laplace.py` isn't Laplace since its scale is `b` rather than `1/b`.

Have now mentioned this in the docs:

image

Have also created several in-doc links to save scrolling. And for consistency have linked more references (some were, some weren't).

**Comment by smk78** [comment]
> @pkienzle commented:
> 
> Better would be to move _Maier-Saupe_ and/or _Cyclic gaussian_ from [examples/weights](https://github.com/SasView/sasmodels/tree/master/example/weights) to `sasmodels/weights.py`, or at least mention that they can be added as user-defined distributions (and add them to the marketplace?)

Have mentioned these distributions in the doc and will also create/populate a Distributions category on the Marketplace.

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on OSX

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on OSX

**Pull request merged**
