### PR TITLE
Sum of three models fix - sasmodels part

### PR DESCRIPTION
**Pull request by rozyczko**
It seems that the reported fixes need to be made to allow for proper handling of the sum of models, of which at least one is already a sum/product.
This fixes the issues of multiple occurrences of parameters in the resulting list.

### CODE REVIEW

**Comment by smk78** [comment]
So can we clarify what issues have been addressed here, please. There were three, all put in by @RichardHeenan:
https://github.com/SasView/sasview/issues/1305
https://github.com/SasView/sasview/issues/1359
https://github.com/SasView/sasview/issues/1360

**Comment by smk78** [comment]
Also, is this fix for just 5.x or for both 5.x and 4.x?

**Comment by rozyczko** [comment]
My comments are only for 5.0

**Comment by rozyczko** [comment]
Currently the same happens with 4.2.

1. Start with empty SasView plugin dir
2. Create a simple sum model (e.g. cylinder + sphere == c_s)
3. Reload -> A_radius and B_radius show up as expected
4. Create a sum of c_s and lamellar == c_s_l
5. Reload the plugins
6. The original c_s will now only have B_radius (which should also be sphere's A_radius)
7. One might try to rename/delete c_s_l.py and observe c_s behaving correctly again

**Comment by butlerpd** [comment]
As per today's conversation this needs some significant restructuring for which there is no current resources to address promptly so remove as a pull request for now

**Comment by pkienzle** [comment]
Removing stale branches. Click restore branch to recover it or apply the following patch:
```diff
diff --git a/sasmodels/mixture.py b/sasmodels/mixture.py
index b0fa2dc0..0da14394 100644
--- a/sasmodels/mixture.py
+++ b/sasmodels/mixture.py
@@ -109,14 +109,17 @@ def make_mixture_info(parts, operation='+'):
                 scale_prefix = ''.join(sub_prefixes) + '_'
             scale = Parameter(scale_prefix + 'scale', default=1.0,
                               description="model intensity for " + part.name)
-            combined_pars.append(scale)
+            # Scale gets added in modelinfo ParameterInfo constructor!
+            if not part.composition:
+                combined_pars.append(scale)
         for p in part.parameters.kernel_parameters:
             p = copy(p)
             p.name = prefix + p.name
             p.id = prefix + p.id
             if p.length_control is not None:
                 p.length_control = prefix + p.length_control
-            combined_pars.append(p)
+            if p.name not in [par.name for par in combined_pars]:
+                combined_pars.append(p)
     parameters = ParameterTable(combined_pars)
     # Allow for the scenario in which each component has all its PD parameters
     # active simultaneously.  details.make_details() will throw an error if
```

**Pull request closed without merging**
