### PR TITLE
use Iqac/Iqabc for the new orientation interface but Iqxy for the old

### PR DESCRIPTION
**Pull request by pkienzle**
Support old Iqxy interface as well as new Iqac/Iqabc interface.   The Iqxy interface is need for functions which operate in 2D data but do not use an orientation transform.  For example, a q-dependent background.  This may also be useful for non-uniform magnetic scattering, which needs more control over the interpretation of q than available in the Iqac/Iqabc interface.

Orientation dispersity is not supported in the Iqxy interface.

### CODE REVIEW

**Comment by pkienzle** [comment]
It is not the same as rotation about the "c" axis since "c" is no longer aligned with "z".

Here is the code for adjusting the view from jitter.py:
{{{
points = Rz(phi)*Ry(theta)*Rz(psi)*points
}}}
Rotations apply in order, so you first rotating the shape by psi about "z" (the "c" axis of the shape), you then rotate by theta about "y", tilting the rotated shape toward the "x" axis of the detector plane, and then again by phi about "z", rotating the tilted shape in the "x-y" plane.

jitter applies first:
{{{
points = Rx(dphi)*Ry(dtheta)*Rz(dpsi)*points
}}}
Again start by rotating the shape about its "c" axis (roll=dpsi), then tilt it into the "x-y" plane as before (yaw=dtheta), and finally rotate in the "y-z" plane (pitch=dphi).  On the wikipedia page for Euler angles (https://en.wikipedia.org/wiki/Euler_angles#Conventions_2) this is the Tait-Bryan z-y'-x'' convention, also know as the nautical angles.

As you can see from playing with explore/jitter.py, jitter creates an orientation distribution on the surface of a sphere determined by yaw and pitch (with roll applied equally at each point in the distribution).  With the pole going along the beam, psi rotates the distribution, theta shifts it to a particular latitude then phi shifts it to a particular longitude.

This description of angles is not usually pertinent to the writer of the model since the translation from qx,qy to qa,qb,qc is handled automatically, but it does belong with the description of orientation for the user in guide/orientation/orientation.rst.

If you update both orientation.rst and plugin.rst so they make sense to you, I can check that they also make sense to me and correspond to what the code is doing.

**Comment by pkienzle** [comment]
BTW, the orientation docs use uppercase Psi but lower case theta and phi.  Is this just because the diagram happens to use an uppercase Psi? 

Also, we have the long axis along Z rather than X, so we are using the Tait-Bryan x-y'-z'' convention, not the z-y'-x'' convention that I claimed earlier.  It is confusing because we have Z going horizontal but the wikipedia article use the usual convention that Z is vertical.  If you instead say the beam is traveling in the +X direction and Z is vertical, then a little airplane flying into the beam would use the usual nautical conventions for roll, pitch and yaw.  This should probably be stated clearly in the docs about orientation.

**Comment by smk78** [comment]
@pkienzle said:

_BTW, the orientation docs use uppercase Psi but lower case theta and phi. Is this just because the diagram happens to use an uppercase Psi?_

Almost certainly!!!

Do we know who has the original construction file for the figure?
(/sasview/build/lib.win32-2.7/doc/_images/elliptical_cylinder_angle_definition1.png)

**Comment by RichardHeenan** [comment]
I have some partial “originals” of some figures, but not of that one, could not be bothered at the time to redo it, so capital psi remained.
Richard

Sent from my Windows 10 phone

**Comment by smk78** [comment]
@pkienzle said:

_Also, we have the long axis along Z rather than X, so we are using the Tait-Bryan x-y'-z'' convention, not the z-y'-x'' convention that I claimed earlier. It is confusing because we have Z going horizontal but the wikipedia article use the usual convention that Z is vertical. If you instead say the beam is traveling in the +X direction and Z is vertical, then a little airplane flying into the beam would use the usual nautical conventions for roll, pitch and yaw. This should probably be stated clearly in the docs about orientation._

But, as things stand, this does actually mean (foresight? coincidence? serendipity?) that (as depicted in /sasview/build/lib.win32-2.7/doc/_images/elliptical_cylinder_angle_definition1.png) we have adopted the same axes convention as [Mantid](http://www.mantidproject.org) .

In Mantid, travelling with the beam is along -Z.

**Comment by smk78** [comment]
I would suggest the following needs to happen in the docs:

1. In /sasmodels/doc/_build/html/guide/plugin.html subsection 10.3.8:

- **change** _corresponding to the x, y and z axes in the laboratory coordinate system_ **to** corresponding to the x (pitch), y (yaw) and z (roll) axes in the laboratory coordinate system

- either add, or link to, elliptical_cylinder_angle_definition1.png (at the moment this subsection is way too dry - albeit with some necessity)

2. Update the note in /sasview/build/lib.win32-2.7/doc/user/sasgui/perspectives/fitting/orientation/orientation.html:

-  with some wording about the order with which rotations will be applied (this is sort of hinted at)

- make some mention of the correspondence between x,y,z and a,b,c as in /sasmodels/doc/_build/html/guide/plugin.html (because we can't be sure which order a reader might come across these two pieces of documentation)

**Comment by smk78** [comment]
Fortunately it would seem  the axes in M_angles_pic.png agree with those in elliptical_cylinder_angle_definition1.png

**Comment by pkienzle** [comment]
None of our models is able to distinguish between positive Z and negative Z (we don't have any airplane-shaped scatters). It would be useful to put in a model without mirror symmetry along the z-axis to confirm that we are using the correct angles.

**Comment by butlerpd** [comment]
Ready for testing on Win64

**Comment by butlerpd** [comment]
@RichardHeenan had concerns about this PR raised in the Tuesday call.  The suggestion was that he was reviewing the wrong branch and he was to retest to verify that his concerns are no longer issues before we merge this request.  Is there an update?

**Comment by RichardHeenan** [comment]
I’m happy, was being rather dumb, that was ticket 1057 which I closed earlier,
Richard

**Pull request merged**
