### PR TITLE
Miscellaneous typo fixes in models

### PR DESCRIPTION
**Pull request by llimeht**
While chasing a different issue, I noticed typos in several of the models. 

- Some of these are in comments or docstrings (first commit). 
- Some are in variable names that may impact on the ability to load old models (second commit) and a compatibility shim might be needed to fix that.

### CODE REVIEW

**Comment by pkienzle** [comment]
The conversion shim is here:
https://github.com/SasView/sasmodels/blob/7fcc745df14565e2ec32b3eb9689ead84c52a6f5/sasmodels/convert.py#L167-L172

We would need to add a clause something like the following (untested) at the end:
```python
if version <= (5, 0, 3) and name == "two_power_law":
    old_pars['coefficient_1'] = old_pars['coefficent_1']
    del old_pars['coefficent_1']
```

**Comment by smk78** [comment]
Apart from the changes in two_power_law.py - which are problematic for the reason above - the remainder all look like straightforward typo fixes in doc strings. Could two_power_law be split out for now so that the remainder could be merged?

**Comment by pkienzle** [comment]
I create #444 for two_power_law. Please remove the change from this PR so we can merge the rest of your corrections.

**Comment by llimeht** [comment]
Split off the changes to two_power_law.py into a separate branch (and rebased this to current master).

**Review by butlerpd — APPROVED** [review]
These are all typo corrections in comments and doc strings and look good. No need for functionality testing given there is no executable code being changed.  This should be ready to merge

**Pull request merged**
