### PR TITLE
Doc gen speedup, improved random model generation and minor fixes

### PR DESCRIPTION
**Pull request by pkienzle**
* model doc generation speedup
    - provide an image cache for the model plots
    - allowing image generation in parallel.
    - delay loading of opencl/cuda so that the GPU initialization doesn't happen until you need it

* sascomp random model generation 
    - RNG sequence changed, so same seed may now produce a different set of model parameters
   - add 'maxdim' as command line parameter (should really follow from q-range of the data instead of being a command line parameter).
   -  polydispersity is preferentially on larger dimensions
   - swap polydispersity with parameters, for example to make sure bell radius is greater than bar radius
   - suppress pd/magnetism no longer inserts pd/magnetism if it wasn't there and is not suppressed, which means that random models with polydispersity occasionally includes monodisperse models.

* sascomp updates
    - add option to display models rather than displaying them on error
    - improve multi-column formatting on list of models
    - *columnize* package is a new optional dependency
    - code cleanup for model parameter generation

* fixes
    - opencl: better error messages if zero length q vector

* cleanup
    - remove *demo* parameters from all the models.
    - polydispersity: rename weights.MODELS to weights.DISTRIBUTIONS; once sasview uses the new name we can delete the old name from weights.

### CODE REVIEW

**Comment by RichardHeenan** [comment]
Just had a look at the code changes for the models so far. So "demo parameters" are deprecated, except where they are actually useful in onion, spherical_sld and unified_power_Rg, as the default parameters don't fully test the model, but demo has never affected the results of sasview itself expect for the separate "compare" testing scripts. So "demo" is not really deprecated? 

I note that hayter_msa has a #TODO 

I presume that to test build the docs from the pak branch that 
python setup.py docs 
will still work, but should we manually delete the old docs directories first ? or do a 
make clean html in the doc directory, exactly which directory is that ? Is it sasview/docs/sphinx-docs or sasmodels/doc ?

**Comment by pkienzle** [comment]
Demo parameters were only available in *sascomp* but it isn't needed since you can set any parameters you want from the command line. They were not used by *SasView*, nor were they used when creating the model plots for the docs.  I stripped them to avoid duplication and remove confusion.

I left the old values there for a couple of cases (the *multiplicity* models) which are not adequately handled by default parameter values as a reminder that we aren't handling them. Do we want to have a multi-shell default model appear when the user selects *onion* in *SasView*?  The *rpa* model plot is particularly boring in the docs, but do we want a complicated model showing up when the user selects it in SasView?

Re: *Hayter-MSA*, the demo parameters were different from the default parameters.  I added the TODO so that someone who knows the model would check that the defaults were reasonable. If so, I'll drop the TODO.

Re: doc builder, these changes make it so that the ESS build system can build the model docs faster in the usual case where the models aren't changing.  Unless we set some new environment variables on our developer machines they shouldn't change how we build things locally.

**Comment by smk78** [comment]
I just built this locally and dip-sticked a whole bunch of pages. As far as doc generation goes this looks good to me.

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on OSX

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on Win

**Pull request merged**
