### PR TITLE
Ticket 608 user defined weights

### PR DESCRIPTION
**Pull request by pkienzle**
Allow a user defined distribution functions by dropping a python file with a Distribution class into the ~/.sasview/weights directory.   No modification to the sasview GUI is required to enable this functionality.

Fits can be saved and reloaded, but the usual problems of sharing fits applies: collaborators might not have the distribution file or they may have a different distribution using the same name.  There is no mechanism for including user-defined models or distributions in the saved project file.

Two examples are provided: example/weights/laplace.py, based on the Laplace distribution in scipy.stats and example/weights/cyclic_gaussian.py.  Set  the following in the environment to activate them:

    SASMODELS_WEIGHTS=path/to/sasmodels/example/weights/*.py

The cyclic Gaussian distribution is equivalent to a Maier-Saupe distribution of order 2, with the interpretation of the width parameter in terms of nematic theory left as an exercise for the user.  This could be modified moved into weights.py as a standard distribution.   

*  [Ticket 608](http://trac.sasview.org/ticket/608) User defined distributions
*  [Ticket 1066](http://trac.sasview.org/ticket/1066) Maier-Saupe distribution

### CODE REVIEW

**Comment by smk78** [comment]
Docs reviewed and some changes made

**Comment by pkienzle** [comment]
I updated the docs a bit more, and made the environment variable more consistent with the other environment variables.  I created [ticket 1138](http://trac.sasview.org/ticket/1138) with further suggestions for environment variables.

I documented how to update the distributions in a running version of sasview (start the python console and type some commands).  We may want support similar to plugin models with gui tools for editing and updating.

**Comment by pkienzle** [comment]
Ae we going to wait until after 4.2 release before merging?

**Comment by smk78** [comment]
Ask on Tue call? (which I won't be on)

**Comment by ajj** [comment]
Works for me and is great new functionality. Will need a separate ticket on enabling editing of this for users. Will also need to have something to scan for added weighting functions while SasView is running, but that is GUI issue. Approving and merging now as it doesn't break regular operation.

**Pull request merged**
