### PR TITLE
ticket-843/870: fix multilayer vesicle polydispersity, docs and parameter names; fixes P*S when parameter names collide

### PR DESCRIPTION
**Pull request by pkienzle**
This will conflict with ticket-815 since which forces n_pairs to be an integer.

### CODE REVIEW

**Comment by ajj** [comment]
Need to check code and behaviour with MultiShell model from Igor. That has a series of caveats that have not come over to the SasView docs. n_pairs does need to be integer since this model is specifically for modelling multilamellar vesicles.

**Comment by butlerpd** [comment]
Yes .... as Andrew says, this model has a number of warnings not ported to SasView. For example the original documentation states:

  " The value returned by the fitting routine for the number of water/shell pairs will be a floating point number. The physical reality must be an integer number of layers. In the model function, the value is truncated so that only the integer portion is used. That is 5.95 "pairs" is actually calculating the scattering for 5 pairs."

With respect to smearing the original documentation states:

  "The resolution smeared version gives the most appropriate view of the model. Note that the resolution 
smearing calculation uses 76 Gauss quadrature points to properly smear the model since the function is HIGHLY oscillatory, especially around the q-values that correspond to the repeat distance of the layers. This can make the calculations rather slow."

Finally it provides a series of usage notes due to the essential instability of the model.  At least these need to be added to the model documentation.

  "This is a highly non-linear model function, complicated by the fact that the number of water/shell pairs must physically be an integer value, although the optimization treats it as a floating point value. For the best possible experience:
	- Start with the best possible guess
	- Using a priori knowledge, hold as many parameters fixed as possible
	- if N=1, tw (water thickness) must by definition be zero. Both N and tw must be fixed during fitting. 
	- If N>1, use constraints to keep N > 1 (set this up in the curve fitting dialog)
	- To force N to "move" during fitting, you may need to set an "epsilon" wave to force a larger step in that direction. epsilon = 0.001 is good for all parameters other than N, which should be set to 1. (set this up in the curve fitting dialog)"

**Comment by pkienzle** [comment]
Re: nomenclature, the docs pretty clearly define shell in pictures, text, and parameter descriptions, and as well as the numbering of the shells.  If you want it to be called pairs, update the diagrams.

Please update docs as appropriate with caveats from the IGOR docs.  Using `sascomp -html multilayer_vesicle` you can easily view the formatted docs.  
(1) Re integer rounding, a number of different models are now rounding to N.  This should be noted in those models, but a general discussion of the effect this has on fitting is not model specific.  That is, don't use derivative based models if you are fitting N. 
(2) Re n=1, Tw is ignored so will allow arbitrary values.  Bumps should return this as an extremely large uncertainty; other fitters should say that the system is singular and they can't compute uncertainty.  Is this so bad?  (Note: I haven't tested fitting simulated data with N=1, but that is what it should do.) 
(3) Re epsilon wave, not sure what you mean.  Are you talking about the epsilon ball radius used in DREAM fitting?  A longer burn-in time will allow DREAM to navigate between steps.

Polydispersity was available in 3.x.  Is it demonstrably wrong?  Can the documentation simply warn that the number of points in the distribution should be increased for this model?

**Comment by butlerpd** [comment]
Latest pull leads to a problem as soon as I try to add the simple S(Q) of HS I get the following error:

Traceback (most recent call last):
  File "C:\Users\Paul\git\sasview_new\src\sas\sasgui\perspectives\fitting\fitpage.py", line 1169, in _on_select_model
    self._on_select_model_helper()
  File "C:\Users\Paul\git\sasview_new\src\sas\sasgui\perspectives\fitting\basepage.py", line 2050, in _on_select_model_helper
    struct_factor())
  File "C:\Users\Paul\git\sasmodels\sasmodels\sasview_model.py", line 179, in MultiplicationModel
    structure_factor._model_info)
  File "C:\Users\Paul\git\sasmodels\sasmodels\product.py", line 60, in make_product_info
    for par in s_pars.kernel_parameters[1:]]
TypeError: suffix_parameter() takes exactly 2 arguments (1 given)

Suggests an error in number of parameters being passed to multiplication model?

**Comment by pkienzle** [comment]
multilayer vesicle has volfraction parameter.  How should this relate to the volfraction parameter in the hard sphere structure factor?

The current code renames volfraction to volfraction_S for the structure factor volfraction in the combined model.

**Comment by butlerpd** [comment]
Latest commit seems to fix the problems and am able to use SQ with the model just fine.  Regarding nomenclature, I still feel that given the model the change was gratuitous but willing to leave as is. 

My only remaining concern is for a somewhat broader consensus on polydispersity.  I really feel that we should avoid n being polydisperse in this release and not convinced about the other parameters, but can easily be overidden - however it should be done "eyes wide open"

**Comment by RichardHeenan** [comment]
I would allow polydispersity on the core radius, in order to damp the oscillations, else the model is not much use in the real world. Defnitely not polydisperisty on number of layers, until we have a robust method for fractions of layers. Polydispersity on the layer thickness likely does not do a great deal for thin layers, so I am tempted not to allow that. For thick layers you probably would not be using this model.

Richard

________________________________

**Comment by pkienzle** [comment]
Integer polydispersity can make sense in some situations.  For example, if the process that creates the pearl necklace adds whole linker+pearl to an existing chain or conversely if a long chains get broken at pearl boundaries, then you will end up with a distribution of integer lengths.  I'm guessing full vesicle shells are also lower energy than partially completed shells? In which case you are going to have a distribution of whole numbered shells.  Currently the only way to express integer polydispersity is through an array because we don't yet allow user-defined distributions.  Gaussian distributions should be okay as well as an approximation to Poisson for large n, with the usual tradeoff between accuracy and computation time.

Suppressing pd on volume parameters will require some work.  n is still needed for computing form volume, so we can't say it is no longer a volume parameter.  Create a ticket for this if you want the capability.  Similarly for parameters that the user can enter but cannot fit.  These could be in the same ticket, since they are both about making the parameter table more flexible.

**Comment by ajj** [comment]
These are the troublesome models that we shelved dealing with in the push for 4.0. Now we must face them. We will need a mechanism to mark polydispersity alone, independent of whether they are needed to calculate volume. Or/And we need full handling of integer parameters, including appropriate default polydispersity (paucidispersity?) distributions for them.

**Comment by pkienzle** [comment]
I added some details on using the array distribution.  I didn't comment on using continuous distributions since that is not likely useful for multilayer vesicles.  A more detailed discussion could be included in fitting/media/pd_help.rst.    Similarly, the fitting documentation should include a section on fitting integer parameters.  I will put these in a ticket for 4.2.

**Pull request merged**
