### PR TITLE
limit pinhole resolution integral to +/- 2.5 dq

### PR DESCRIPTION
**Pull request by pkienzle**
See sasview ticket http://trac.sasview.org/ticket/1102

This changes the computed pinhole resolution values, so they are now different from older versions of sasview and Igor.  The tests against the old values have been suppressed.  Instead, the code was verified by comparing the Pinhole1D calculation against the direct integral using Romberg integration.  The demo could be turned into a new test case.

### CODE REVIEW

**Comment by butlerpd** [comment]
@pkienzle chose 2.5 sigma based on the work of Barker & Pedersen (1995).  Basically the resolution can be approximated by a **truncated** Gaussian, but including the long tails will lead to incorrect results. However as @pkienzle points out there is a bit of ambiguity as to whether a +/-2.5 or +/-3.0 sigma cutoff would be best. The paper states:
> The Gaussian method produces fair agreement withh the numerical arc method only by truncation of the Gaussian functions to +/- 2.5 sigma.  Extending the tails to just +/- 3 sigma increase the error intolerably.
>
 and later
> Truncating the Gaussian functions at +- 2.5 sigma agian gives the best agreement with the numerical calculation.
>
although it later says
> Here, 2.5 sigma and 3 sigma are chosen only as example truncation limits, with the ideal truncation limits for obtaning good agreement dependent upon the instrumental configuration parameters, and the scattering profile.
>
John Barker agrees that 2.5 would be best.

@pkienzle also notes:
> Limiting the resolution integral to 2.5 sigma on a 1/q^4 power law model I fit the following slopes:
    -4.00 for 20% dq/q
    -3.98 for 30% dq/q
    -3.92 for 35% dq/q
    -1.15 for 40% dq/q
So assuming we keep under 35% dq/q then the fits won't be too badly behaved.
>

My own testing indicates that the basic obvious problem is fixed when fitting the attached power law type data.  However there is an extremely disturbing problem:
If one plots the power law function with default parameters and min max q and then chooses a constant dq% (dq/q), the resulting curve depends sensitively on both the number of points used (default is 50) and much more sensitively on whether choosing those points spaced linearly or logarithmically.  To really exacerbate choose a 60% sigmaq/q and 300 points.  log spacing will produce a power law of smaller slope but much higher intensity.  If one then unclicks the log spacing of points to get linear spacing of points, the curve totally changes to something unrecognizable.  This clearly seems very very wrong.  The curve should not depend on what points we choose to plot should it? Not sure if the problem is in the smearing algorithm or in the GUI ... but suspect it is in sasmodels.

I note that John Barker also has concerns that:
>If the power law model follows I(q) = Aq^-m  
and If you use a "box" shaped resolution function and choose  resolution dq = const , (where collimation is dominant),   the smeared intensity is
`Is(q) = A q^-m + B (dq/q)^2 q^(-m-2)`
So for data near the beam stop and  m = -4 , the slope on a log-log plot should decrease from -4  down  to a limit of -6.
If wavelength smearing is dominant, where dq/q ~ q,
`Is(q) = (1 + C (dq/q)^2 ) q^-m`
the slope should not change at all, yet you see a large decrease in the slope.
>
Thus this does seem to fix the obvious problem that was reported but I think some further investigation would be appropriate before merging this PR?

**Comment by pkienzle** [comment]
2.5 sigma for 40% dq/q means that every point integrates over q=0, which should yield infinity.  Keep the resolution less than 40%.

Regarding linear points, we have a ticket asking to calculate q points between measured points for the resolution calculation so that every point has a basis of support (ticket 715 and 717).

**Comment by ajj** [comment]
Two comments.

1) IGOR currently used +/- 3 sigma, nominally following a paper by John! However, it also truncates so that no negative Q values are included. 

2) Limiting sigmaQ/Q to less than 40% is not possible - experimentally the lowest Q points often have 50% sigmaQ/Q or worse due to the geometric part of the resolution function.

**Comment by butlerpd** [comment]
Some more comments:

1) My recollection with NCNR SANS data is that we regularly have 25% up to maybe 40% at the lowest q point (near beam stop).  The example data in the ticket has a maximum of about 31% on the lowest q point of the 15m data (24% I think for the 1m data).  Not sure I've actually seen 50%.  Do you have an example Andrew?
2) Pertinent to ESS - what will the resolution look like on LOKI? will a Gaussian approximation still work? Maybe the > 50% comes from LOKI simulations Andrew?  At which point this becomes an issue!
3) regarding sampling and ticket #715 I believe the way Steve gets around this problem in IGOR is simply to use a Gaussian quadrature approach which picks the "best Q sampling" for each calculated point?  This however I think is much more expensive?

FINALLY - BIG QUESTION:
Should we truncate at zero Q? Or are negative Qs appropriate/physically being included (basically extending through the main beam to the other side?).  If negative Q should be kept, how then to handle zero Q which is often not defined in the models.

**Comment by butlerpd** [comment]
Also - regarding canSAS formats; NXcanSAS defines a very flexible entry for resolution which can even define non Gaussian functional forms.  The problem however is for analysis software to know what to do with it. Or more correctly speaking, there is a chicken and egg problem: instruments writing reduced data and analysis software consuming that data need to agree on what is needed.

**Comment by wtheller** [comment]
For what it is worth, Ken Littrell truncates at q=0.  I do the same.  I did allow q<0 by accident recently in the machine learning training code, which does not use the built-in smearing.  It causes an odd-looking pile-up at very low Q when dQ/Q is large.  Sorry, I don’t recall how large, but the behavior was visible for most dQ/Q that I was randomly generating while testing.

**Comment by butlerpd** [comment]
Note that there is a resolution test failing ... but this will probably change again as soon as we change how we want the code to behave so not worried for this interim merge.

**Pull request merged**
