### PR TITLE
Fix docs and code for be_polyelectrolyte.py

### PR DESCRIPTION
**Pull request by butlerpd**
Docs were fixed as explained in ticket #1155 as was the code.  A
validation note was added to docs to indicate change and the fact that
full validation has not really been done.  Also all unit tests that had
non-zero salt concentration values have been commented out till we
decide how to handle the change in terms of validating unit tests.

### CODE REVIEW

**Comment by pkienzle** [comment]
(1) I have been leaving out docstrings from Iq because duplication.  Others have been putting them in because pylint.  If necessary, they could be added at runtime using the same code used to put the parameter table in the sphinx documentation.  Maybe compromise and say: "See parameter table."?

(2) Ideally find an independent check that the values are correct (such as a limiting condition, values from the original paper or cross check against other software).  Putting in the currently computed values does have some benefit in that we can notice when an underlying library changes and code no longer produces the same value.

**Comment by butlerpd** [comment]
good catch on units of C_s and C_a ... but the new units are 1/V so 1/|Ang|^3 not 1/|Ang| (same mistake I made in the validation section that Richard caught me out on).  Will try to fix when I get to a development machine.

Given that I am 99% sure this is now correct do we really want to add the note before the Definition section?  This should be a rather dire warning - If so I believe there are quite a few models with much iffier caveats we should be going through and doing that for.  For the paracrystalline which we believe is wrong I agree that a dire note before "definition" is the right thing to do, unless we fix them - but as of last night I don't think that will be a 4.2 fix

**Comment by smk78** [comment]
Have changed the 1/|Ang| to 1/|Ang^3|.

**Comment by smk78** [comment]
Just to respond on @butlerpd's second point. I added a Note to the top of be_polyelectrolyte. What I added to the paracrystal models was a Warning. The appear differently when rendered.

**Pull request merged**
