### PR TITLE
core_shell_parallelepiped: rewrite so that integrated 2D matches 1D

### PR DESCRIPTION
**Pull request by pkienzle**
branched off the ticket-776 branch (which has a new 2D model interface), replaces the core shell parallelepiped 1D kernel with a version that matches the integrated 2D kernel, and also the algorithm of the hollow rectangular prism

### CODE REVIEW

**Comment by pkienzle** [comment]
It seems all the changes I'm doing in the ticket-776 branch are showing up as changes in this branch.  Ignore them, and only look at the change to core_shell_parallelepiped.c

**Comment by pkienzle** [comment]
core shell parallelepiped does not match hollow rectangular prism, even after volume correction.  Still looking into it.

**Comment by dehoni** [comment]
For me it worked after a redefinition of the core sld against the shell sld. Otherwise the core term simply drops zero, i.e. there is no constrast between core and shell. Attached you can find the code after cleaning-up and collecting terms. In the end this is a new model: (non truncated) core-shell parallelepiped.
[core_shell_parallelepiped_test_hollow_prism.txt](https://github.com/SasView/sasmodels/files/1443093/core_shell_parallelepiped_test_hollow_prism.txt)

**Comment by pkienzle** [comment]
I posted a new version allowing different sld for a, b and c end caps.  I added the ```OVERLAP``` flag in the code to switch between end caps that overlap to form an enclosing box (which I need to match hollow rectangular prism) vs. end caps which are the same size as the core face, leaving the edges and corners unfilled.

To make things match I had to change the volume normalization to exclude the core for hollow_rectangular_prism, or include it for rectangular_prism comparison.  I put in a ticket asking if the volume normalization should include a contrast factor.

**Comment by RichardHeenan** [comment]
The new OVERLAP=1 version would now be nicely included as a separate model (this is where a control flag, non-fittable, type parameter in models would be useful).

Looking at the code I suspect that the "keep A<B<C" note is not relevant.

For "hollow_particle" models, the volume normalisation should I think for consistency use the volume of the shell, whilst for any "core_shell_particle" the normalisation should use the total volume of the particle (regardless of whether the contrast chosen has made either the shell or the core "invisible", it then being up to the user to sort what they need).

**Comment by pkienzle** [comment]
I think the answer is not that a < b < c, but rather that we do not support large structures at high q.  This is a general rule having to do with how we perform our integration that applies to all the models unless explicitly stated otherwise (for example, we could detect long rods at high q in the cylinder model and switch algorithms internally and document that in the model description).

For the "overlap" core shell parallelepiped, the choice of axes is determined by geometry: the "c" cap covers the "a" and "b" core and rim, the "b" cap covers the "a" rim, and the "a" cap only covers the "a" face.  This is independent of the ordering of the lengths.

For the "non-overlap" core shell parallelepiped, the code for "a" and "b" is completely symmetric, but the choice of "c" does determine the order of integration, and so might affect the preferred ordering.  You can compare as follows, with a-> b -> c -> a:
```
./sascomp core_shell_parallelepiped -double length_a=,length_c length_b=,length_a length_c=,length_b thick_rim_a=,thick_rim_c thick_rim_b=,thick_rim_a thick_rim_c=,thick_rim_b sld_a=,sld_c sld_b=,sld_a sld_c=,sld_b
```
Some models show a difference at high q for large structures because the number of integration steps is too low.  I coded core_shell_parallelepiped (non-overlap) into explore/asymint.py, and for the particular case I chose I found that setting "c" to the shortest axis gave better numerical performance.

**Comment by pkienzle** [comment]
When cleaning up the latex to make the equations match the implementation I noticed that the volume terms could be broken up and attached to the individual terms as ```SL = L sin(Q_L L/2)/(Q_L L/2)```.  When multiplying ```SA*SB*SC```, the volume term ```V = A*B*C``` magically appears.

I updated the code to match these new simplified equations and checked that they produced the same results as before.

In checking the docs I noticed that we claimed to sort the axis lengths when computing ER, but the code was not.  I updated ER to use the same algorithm as parallelepiped.

The docs still say that ```A < B < C```.   Running sascomp, it is easy to see that the order matters:
```
./sascomp parallelepiped length_a=length_a,length_b length_b=length_b,length_c length_c=length_c,length_a -sets=1 -double! -pars
```
The difference might have to do with the ```u=cos alpha``` substitution in the 1D integration, which may lead to better numerical behaviour when the long axis is C.  The same would apply to all elongated shapes.  Not sure which is more correct.

**Comment by pkienzle** [comment]
Check the scale factors on all the box models.  

The inner sum, which is integrating over [0, pi/2] is being scaled by 1/2 rather than pi/4.  The reason for the pi/4 is because the gauss control points range over [-1, 1] and the target integral ranges over [0, pi/2].  An additional factor of 8 is needed since the integral is over a single quadrant rather than the whole 4 pi.  Or maybe the equations in the docs are missing a 1/(4 pi) normalization factor.

The triaxial ellipsoid model scales by 4 rather than pi/4 because of the 8/(4 pi) normalization.

**Comment by butlerpd** [comment]
A few comments/questions on the code
* Only Iqxy seems to be define which only works with old orientation?  in pull request #58 that appears to change to Iqabc. Is the code otherwise the same? Also there is then no Iqxy so no longer compatible with old? that may be correct but unsure of compatibility question here.
* Comment in line 122 to 123 is no longer valid ... the code IS the same as 1D since the scaling was removed from 1D
* leading to the question ... shouldn't the 1D just call the 2D rather than reimplement? The code seems the same essentially but then integrated over full orientation distribution (instead of just a "jiggle")

In the Python module the provenance part of the docs need updating.

I still have not checked the docs properly - but we could merge everything and fix docs later if needed in order to get things moving?

**Comment by pkienzle** [comment]
* Iqxy -> Iqac/Iqabc in #57 so that the old Iqxy interface can still be supported.
* comment corrected #57
* 1D duplicates code in 2D so that the inner loop can precompute siC/siCt; this drops the number of calls to sin() from 7 n^2 to 5 n^2, so reusing code would be 40% slower.
* authorship/verification updated in #57

**Pull request merged**
