### PR TITLE
sasview 1534: use source hash as part of dll name to avoid collisions

### PR DESCRIPTION
**Pull request by pkienzle**
See https://github.com/SasView/sasview/issues/1534

Different versions of sasview on the same machine will end up using the same dll files, causing crashes and unexpected results.

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on OSX

**Comment by wpotrzebowski** [comment]
It seems to work fine with 5.x branch however when testing against 4.x master I get the following ERROR : sas.sasgui.guiframe.gui_manager (gui_manager.pyc:3278) :: gui_manager.clean_plugin_models:
  [Errno 30] Read-only file system: '/Volumes/SasView-4.2.2-MacOSX/SasView 4.2.2.app/Contents/Resources/plugin_models/__init__.py'

This may be unrelated to this though as user who reported bug #1534 experienced it with 4.2.2 release.

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on Win

**Comment by pkienzle** [comment]
The 4.2 app cannot run from the dmg.  For reasons unknown, the installer adds files to the app (`Contents/Resources/plugin_models/__init__.{py,pyc}`) which the application then tries to delete when it starts up.  Since a dmg disk image is write-only this unsurprisingly fails when you try to run the app from within the mounted image.  Moving the app outside the disk image (e.g., dragging it to the desktop) and running, then it starts fine.  When I look into the .app directory I see that the `__init__.{py,pyc}` files are indeed gone.

I tried the sasview jenkins build [1055](https://jenkins.esss.dk/sasview/job/SasView_OSX10.10/1055/). Running from within the dmg I got the expected write-only error. However, moving the app outside the .dmg I no longer got that error, but the fitting perspective isn't loading.  No hints in sasview.log why this might be.

**Pull request merged**
