### PR TITLE
Reparameterize existing model. Refs SasView/sasview#501.

### PR DESCRIPTION
**Pull request by pkienzle**
See SasView/sasview#501, #207 .

Create a model derived from an existing model with parameter changes.

Advantage compared to constraints in the UI is that the constraints are stored in the model and don't need to be set every time they are needed.  Disadvantage is that the derived model need to be named and stored as a plugin.  Plugins are not currently stored with the fit, and need to be copied separately when sharing saved fit files.

### CODE REVIEW

**Comment by pkienzle** [comment]
Note: does not work with array parameters such as shell thickness in the onion model.

**Comment by butlerpd** [comment]
ok .. I am a bit confused... so is this meant to allow a user to create a plugin model that calls an existing model and add some parameters with constraints by reusing the existing code rather than embedding it in the new model? More elegant I guess but the infrastructure changes scare me a bit :-)  I guess this supports both python and c models intrinsically since it is just a python wrapper to an existing model?

**Comment by pkienzle** [comment]
Example model, *ellipsoid_by_volume.py*:
```python
from numpy import inf
from sasmodels.core import reparameterize
parameters = [
    # name, units, default, [min, max], type, description
    ["volume", "Ang^3", 1e5, [0, inf], "volume", "ellipsoid volume"],
    ["eccentricity", "", 1, [0, inf], "volume", "polar:equatorial radius"],
]
translation = """
    Re = cbrt(volume/eccentricity/M_4PI_3)
    radius_polar = eccentricity*Re
    radius_equatorial = Re
    """
model_info = reparameterize('ellipsoid', parameters, translation, __file__)
```

This is not a simple wrapper, but instead a simple modification to the source template.  

Inside the innermost polydispersity loop it introduces the statement
```c
const double _var_Re = cbrt(local_values.volume/local_values.eccentricity/M_4PI_3);
```
Then it does the following to call `Fq`:
```c
Fq(q, &F1, &F2, local_values.sld, local_values.sld_solvent, local_values.eccentricity*_var_Re, _var_Re);
```
Similarly for `form_volume` and `Iqac`.

This is only implemented for C models.  Something similar could be done for python models, or perhaps we could use a python to C translator so we don't have to implement every change in two places.

---

You could create the model on-the-fly from the GUI.   Just provide a "new parameter" button at the bottom of the model page, click it three time, and enter the parameter names (*volume*, *eccentricity*, *Re*), then set 
* *Re* to `=cbrt(volume/eccentricity/M_4PI_3)`,  
* *radius_polar* to `=eccentricity*Re`, and
* *radius_equatorial* to `=Re`

Default the units to "", the value to 0., the range to [-inf, inf], and set the description to name.  Use "volume" as the type so that all new parameters are polydisperse.

Be sure to include enough information in the save file that you can recreate it on load.

---

The test cases use the on-the-fly definition, so we now know this will work for OpenCL (and for DLLs after a couple of fixes).

We will need a similar on-the-fly model to support the local-monodisperse interaction model, where we integrate `P(q,r) * S(q, r_eff)` over polydisperse `r`.

**Comment by RichardHeenan** [comment]
OK, so I have been asked to review this, but other than read the code, which seems to have a built in example, I'm not clear how I can test it. The principle however seems good. As far as users are concerned their experience is going to be down to adding extra parameters via the gui, for which we would have to write more code, and which is something that I very much like to see happen. Doing this in an way which is easier than simply hacking the existing model is obviously key,

I am assuming that if we merge this PR it would not or could not possibly break anything else???

**Comment by pkienzle** [comment]
Richard, I'm not asking for a code review, just a comment on whether the approach is sufficient.

This allows a series of assignments to intermediate values using only values from the calling parameter table, finally assigning expressions of intermediates and calling parameters to the base parameter table.  So no loops and no complicated if blocks.  You can use simple conditionals:
```
    c = (condition ? a : b)
```

You can cross check against fish results by a plugin model such as *ellipsoid_by_volume.py* above and save it into your .sasview/plugins directory.

There may be other approaches, such as #215 which suggests enumerating all possible variants in the kernel code, or just [copy and modify an existing model](https://github.com/SasView/sasview/issues/501#issuecomment-478225264).

I agree with PaulB that hacking this into the infrastructure is a bit scary: the more features we stuff in like this the harder it is going to be to stuff in new features later.   I welcome suggestions for a better way to do this, and someone to do a code review.

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on OSX

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on Win

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on Win

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on Win

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on OSX

**Comment by wpotrzebowski** [comment]
@pkienzle: does it work with sasview 4.x only?

**Comment by pkienzle** [comment]
Should work with all versions.

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on OSX

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on OSX

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on Win

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on Win

**Comment by gonzalezma** [comment]
It works as expected and seems a good enhancement to me, but I found a problem with the interface (tested on Windows 10). The issue is that the new parameters appear in the interface (together with the global ones: scale and background), but not the other parameters (e.g. sld and sld_solvent in the ellipsoid example). A trivial workaround is to add also those parameters to the list of the reparameterized model (e.g. new_sld, as using just sld gives a duplicate parameters error) and the corresponding translation (sld =new_sld), but ideally one should find a better solution.

**Comment by pkienzle** [comment]
Works in sasmodels and sasview master (wx 4.x branch).

Plugins aren't working at all for me in the ESS_GUI branch right now.  Perhaps because I have broken plugins in my plugins directory?  Haven't tried debugging.

**Comment by gonzalezma** [comment]
Correct. I tried in SasView 5.0, using the Windows10-ghprb build. Apart from this interface issue, the functionality added by this solution looks really good to me. I asked Sylvain Prevost and Lionel Porcar here at the ILL to try it and tell us if this could be helpful for the kind of problems that they had in mind when they asked for a flexible way of 'customizing' the existing models, but it can take some time before they are able to answer.

**Comment by RichardHeenan** [comment]
After much discussion with Paul K,  here is a further example, a re-parametrised core_shell_ellipsoid, which solves a cubic on the fly for thick_shell when there is solvent in the shell. Paul invented a way to pull in the c code for the solver routine, a better way is in progress.  (.py and .c files renamed .txt to get them to load here)

[cubic_solve_reparam2.txt](https://github.com/SasView/sasmodels/files/3443394/cubic_solve_reparam2.txt)
[core_shell_ellipsoid_reparam2.txt](https://github.com/SasView/sasmodels/files/3443395/core_shell_ellipsoid_reparam2.txt)

**Comment by pkienzle** [comment]
New version allows C source containing translation function to be included:
```python
model_info = reparameterize('core_shell_ellipsoid', parameters, translation,  
        __file__, source=['cubic_solve_reparam2.c'])
```

**Comment by RichardHeenan** [comment]
Here is latest version, with more unit tests and an improved cubic solver, and an xls that will compute thick_shell for users to check the value being used.

**core_shell_ellipsoid_reparm3.py**

from numpy import inf

from sasmodels.core import reparameterize

parameters = [

    # name, units, default, [min, max], type, description

    ["vol_dry_shell_over_core", "None",    0.75,   [0, inf],    "volume",         "volume ratio of dry shell to core"],

    ["sld_dry_shell",           "1e-6/Ang^2", 1,   [-inf, inf], "sld",      "Dry shell scattering length density"],

    ["f_solvent_in_shell",      "None",       0.3, [0.0, 0.99], "volume",      "Local volume fraction of solvent in wet shell"],
]

translation = """

    thick_shell = solve_shell_v3(radius_equat_core, x_core, vol_dry_shell_over_core, x_polar_shell, f_solvent_in_shell)

    sld_shell = f_solvent_in_shell*sld_solvent + (1-f_solvent_in_shell)*sld_dry_shell

    """

model_info = reparameterize('core_shell_ellipsoid', parameters, translation, __file__, source=['cubic_solve_reparam3.c'])

# Note: adding unit tests using the following:

model_info.tests = [
    # first replicate all five tests from core_shell_ellipsoid
    [{'radius_equat_core': 200.0,
      'x_core': 0.1,
      'vol_dry_shell_over_core':1.34375,
      #'thick_shell': 50.0,
      'x_polar_shell': 0.2,
      'sld_core': 2.0,
      'sld_dry_shell': 1.0,
      'sld_solvent': 6.3,
      'f_solvent_in_shell':0.0,
      'background': 0.001,
      'scale': 1.0,
     }, 1.0, 0.00189402],

    # Additional tests with larger range of parameters as per core_shell_ellipsoid
    [{'radius_equat_core': 20.0,
      'x_core': 3.0,
      'vol_dry_shell_over_core':8.3751,
      #'thick_shell': 30.0,
      'x_polar_shell': 1.0,
      'sld_core': 2.0,
      'sld_dry_shell': 1.0,
      'sld_solvent': 6.3,
      'f_solvent_in_shell':0.0,
      'background': 0.01,
      'scale': 1.0,}, 0.1, 11.6915],

    [{'radius_equat_core': 20.0,
      'x_core': 200.0,
      'vol_dry_shell_over_core':13.2444500,
#      'thick_shell': 54.0, - this case has +ve determinant
      'x_polar_shell': 3.0,
      'sld_core': 20.0,
      'sld_dry_shell': 10.0,
      'sld_solvent': 6.0,
      'f_solvent_in_shell':0.0,
      'background': 0.0,
      'scale': 1.0,
     }, 0.01, 8688.53],

    # 2D tests  as per core_shell_ellipsoid
    [{'radius_equat_core': 20.0,
      'x_core': 3.0,
      'vol_dry_shell_over_core':8.375001,
      #'thick_shell': 30.0,
      'x_polar_shell': 1.0,
      'sld_core': 2.0,
      'sld_dry_shell': 1.0,
      'sld_solvent': 6.3,
      'f_solvent_in_shell':0.0,
      'background': 0.001,
      'theta': 90.0,
      'phi': 0.0,
     }, (0.4, 0.5), 0.00690673],

    [{'radius_equat_core': 20.0,
      'x_core': 200.0,
      'vol_dry_shell_over_core':13.2444500,
      #'thick_shell': 54.0,
      'x_polar_shell': 3.0,
      'sld_core': 20.0,
      'sld_dry_shell': 10.0,
      'sld_solvent': 6.0,
      'f_solvent_in_shell':0.0,
      'background': 0.01,
      'scale': 0.01,
      'theta': 90.0,
      'phi': 0.0,
     }, (0.0866025403, 0.05), 0.01000025],

     # 1D using new parameters - not checked by other means
    [{'radius_equat_core': 20.0,
      'x_core': 3.0,
      'vol_dry_shell_over_core':0.75,
#      'thick_shell': try 7.88356 with x-polar_shell=0.5 - this case has +ve determinant
      'x_polar_shell': 0.5,
      'sld_core': 2.0,
      'sld_dry_shell': 1.0,
      'sld_solvent': 6.3,
      'f_solvent_in_shell':0.3,
      'background': 0.01,
      'scale':0.1,
     }, 0.025, 26.45088379],
     # 1D using new parameters - not checked by other means
    [{'radius_equat_core': 20.0,
      'x_core': 3.0,
      'vol_dry_shell_over_core':8.0,
#      'thick_shell': try 50.0 with x-polar_shell=0.0 - this case is quadratic
      'x_polar_shell': 0.0,
      'sld_core': 2.0,
      'sld_dry_shell': 1.0,
      'sld_solvent': 6.3,
      'f_solvent_in_shell':0.2888889,
      'background': 0.01,
      'scale':0.1,
     }, 0.05, 11.83784036],
]

[cubic_solve_reparam3.txt](https://github.com/SasView/sasmodels/files/3457712/cubic_solve_reparam3.txt)
[core_shell_ellipsoid_simple_01Aug2019.xlsx](https://github.com/SasView/sasmodels/files/3457713/core_shell_ellipsoid_simple_01Aug2019.xlsx)

**Comment by pkienzle** [comment]
It would be easy enough to add functions to the reparameterized model which calculates extra values outside the kernel and stores them in a dictionary that can be returned for the model.  This could be added to the data tree like the other intermediate values so you don't need to put it in the kernel.  This would remove the need for the additional spreadsheet.  Averaging this calculation over polydispersity is more difficult since that currently happens inside the kernel calculation.

We already have the notion of returning extra information from interaction and mixture models: a results dictionary with the individual S and P calculations.  Not sure it is general enough to handle arbitrary key: value pairs.

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on OSX

**Comment by wpotrzebowski** [comment]
sasmodels ready for testing on OSX

**Comment by RichardHeenan** [comment]
The bug mentioned above is still there (at least in my local Win10 v5 build of master). The remaining parameters, not included in the constraint, do not appear in the gui, though are obviously working stuck at their default values.

**Pull request merged**
