### PR TITLE
ticket-835: allow negative q in resolution calculation

### PR DESCRIPTION
**Pull request by pkienzle**
Use abs(q) when computing negative q values for resolution calculations.

This still doesn't address the problem where a sample q point happens to lie at q=0 for a model which diverges at q=0.  Perhaps adjust any points where |q| < Qmin to q=Qmin, with Qmin = 0.1*min(q) to protect against this?

### CODE REVIEW

**Comment by RichardHeenan** [comment]
After discussion with Andrew, we think that the models ought to deal with both Q<0 and Q=0, not the smearing routine. If needs be all the models should do Q = abs(Q) when they start.  Thus the fractal model in ticket #835 should be modified.  
To avoid issues with the few models that actually diverge or are undefined at exactly Q=0, then the smearing routine could avoid Q=0 when extrapolating. How does the smearing choose values to use when extrapolating?  [I'm not clear either whether the smearing only interpolates the theory curve at the user supplied Q points, or whether it calculates extra theory points on a finer grid, as it ought to if it is going to get decent results on curves with sharp dips & peaks. Really we ought to have options for "fast" smearing where there are no really sharp features or "slow but accurate".]

**Comment by pkienzle** [comment]
Note: responded directly in trac [http://trac.sasview.org/ticket/835#comment:7]

**Comment by smk78** [comment]
See response in trac http://trac.sasview.org/ticket/835#comment:9

**Comment by butlerpd** [comment]
From Richard
Use abs(q) when computing negative q values for resolution calculations.

This still doesn't address the problem where a sample q point happens to lie at q=0 for a model which diverges at q=0. Perhaps adjust any points where |q| < Qmin to q=Qmin, with Qmin = 0.1*min(q) to protect against this?
I think this would be OK, might go smaller still, say 0.02*min(Q) ?
Richard

**Comment by butlerpd** [comment]
testing roles of reviewers/assignees -- this needs more work

**Comment by butlerpd** [comment]
why is this not allowing me to review?

**Comment by pkienzle** [comment]
Closing temporarily since it is not yet ready to merge.

**Comment by pkienzle** [comment]
The algorithm now excludes q values in (-0.02 qmin, 0.02 qmin).  There may still be points at negative q if the delta q at qmin is large.  In the rafal dataset, which extrapolates from the q range (0.001547381, 0.4673276) to the q range (-0.0004811488, 0.58678529), the extrapolation uses the following points:
```
 -0.00048115 -0.00022758 --- 0.00027955 0.00053312 0.00078668 0.00104025 0.00129381
```
with the point near zero excluded.  From this set of q centers, it computes mid points between each and uses the error function to integrate the gaussian value between those midpoints.  It then takes the absolute values of the q centers since q at -0.00048115 is the same as q at 0.00048115, but still associates them with the distribution weights for the negative q values.

**Comment by pkienzle** [comment]
Question: can USANS resolution include negative q values at the lowest q?  Currently the algorithm uses logarithmic spacing for extrapolating, but it would be easy enough to use linear extrapolation at low q with:
```
diff --git a/sasmodels/resolution.py b/sasmodels/resolution.py
index 73cc553..c4592df 100644
--- a/sasmodels/resolution.py
+++ b/sasmodels/resolution.py
@@ -354,9 +354,12 @@ def slit_extend_q(q, width, height):
     that each point I(q) has sufficient support from the underlying
     function.
     """
-    q_min, q_max = np.min(q-height), np.max(np.sqrt((q+height)**2 + width**2))
+    data_min = np.min(q)
+    q_min, q_max = data_min-height, np.max(np.sqrt((q+height)**2 + width**2))
 
-    return geometric_extrapolation(q, q_min, q_max)
+    # geometric extrapolation above, linear extrapolation below
+    q = geometric_extrapolation(q, data_min, q_max)
+    q = linear_extrapolation(q, q_min, q_max)
```

**Comment by butlerpd** [comment]
I believe this is reasonable.  has the last comment been moved to a ticket to be looked into later?  If Richard and/or Andrew don't have time to verify their concurrence in the next few days I will "approve changes" on my (nominal - actually was for Richard) request.

**Comment by pkienzle** [comment]
Ticket #878 says to reconsider low-resolution USANS.

**Pull request merged**
