### PR TITLE
Add local link to source files.  Refs #1263.

### PR DESCRIPTION
**Pull request by pkienzle**
[Ticket 1263](http://trac.sasview.org/ticket/1263)

This copies the model sources to the doc tree (if they are newer) and links to them from the model doc.  We need to do this because sphinx can't link to an absolute path.

It would be nice to have syntax highlighting on the code, but I didn't see an easy way to do so.

Instead of linking to the files, we could easily link to the github repo, either for the sasmodels verstion or to master.

### CODE REVIEW

**Comment by pkienzle** [comment]
I'll change it to a latex symbol rather than unicode.  It will remove the file write error, and it will work in latex transparently as well.

Note: could also have tried the following, which should work in python 2 and 3:
```
 io.open(sys.argv[2], 'w', encoding='utf-8').write(docstr)
```

**Comment by smk78** [comment]
Merged updated fitting_sq.rst from master into this branch

**Comment by smk78** [comment]
Switched to this branch and issued make clean html. Got this error which I don't get in a build from master:
```
C:\Code\sasmodels\doc\index.rst:44: ERROR: Unknown directive type "htmlonly".

.. htmlonly::
   :Release: |version|
   :Date:    |today|

   Download pdf version `here <SASModels.pdf>`_
C:\Code\sasmodels\doc\index.rst:65: ERROR: Unknown directive type "htmlonly".

.. htmlonly::
  * :ref:`search`
```
But otherwise the auto-linking to the python and c source seems ok.

**Comment by pkienzle** [comment]
The *only* directive was removed from recent versions of matplotlib and added to sphinx.  We should bump the sphinx version to 1.8 in the build system, and in places such as:

    sasview/build_tools/conda/ymls/sasview-env-build_win.yml

We could instead do the following in sasmodels/doc/conf.py:
```
extensions = [ ... ]

try:
    # only directive was added to sphinx and removed from matplotlib
    import matplotlib.sphinxext.only_directives
    extensions.append('matplotlib.sphinxext.only_directives')
except ImportError:
    pass
```
but that will fail if you have a new matplotlib but an old sphinx.

**Comment by smk78** [comment]
So I bumped my Sphinx to 1.8.5 but I still get the htmlonly warning.

```
Checking Required Package Versions....

Common Packages
reportlab Version Installed: 3.3.0
lxml Version Installed: 3.6.4.0
PIL Version Installed: 1.1.7
xhtml2pdf Version Installed: 3.0.33
pyopencl NOT INSTALLED
unittest-xml-reporting Version Installed: 2.1.0
pylint Installed (Unknown version)
matplotlib Version Installed: 1.4.3
bumps Version Installed: 0.7.6
scipy Version Installed: 0.17.1
periodictable Version Installed: 1.5.0
setuptools Version Installed: 40.8.0
h5py Version Installed: 2.6.0
sphinx Version Installed: 1.8.5
pyparsing Version Installed: 2.3.1
numpy Version Installed: 1.10.4
html5lib Version Installed: 0.999
wx Version Installed: 3.0.0.0

Windows Specific Packages:
pywin Version Installed: unknown
py2exe Version Installed: 0.6.9
comtypes Version Installed: 1.1.2

Deprecated Packages
You can remove these unless you need them for other reasons!
pyPdf NOT INSTALLED
```

**Comment by pkienzle** [comment]
The `only_directives` module was removed from matplotlib for matplotlib 3.0.  Instead, they are using the `only` directive, which has been in sphinx since at least version 1.0 (2011).  I've changed references in sasmodels.  I don't see any in the sasview docs.

**Comment by smk78** [comment]
Docs in this branch now build fine so am merging this branch.

**Pull request merged**
