### PR TITLE
Spherical boucher model

### PR DESCRIPTION
**Pull request by dehoni**
This PR adds a Boucher-type SLD profile to the selection in the model spherical_sld.

### CODE REVIEW

**Comment by butlerpd** [comment]
The files changed include the broad peak model not just the spherical SLD?  Also is this gong to cause problems with old projects?

**Review by krzywon — APPROVED** [review]
This PR could be merged as-is if the changes to `broad_peak.py` were omitted. I just approved the broad peak model changes, but with a discussion topic, so this PR should either wait until that discussion is resolved, or the `broad_peak.py` changes are removed. Another set of eyes on the mathematics wouldn't hurt, either.

There was concern about whether this model would need an entry into the conversion table, but as long as any new `shape` factor comes after existing factors, this type of model change should not affect backwards compatibility with any `sasview` or `sasmodels` features.

**Review by krzywon — CHANGES_REQUESTED** [review]
@dehoni - Your latest commit will undo the changes made in the broad peak branch even after that branch is merged because this new commit will be later in the overall commit history. This only just dawned on me otherwise I would have suggested against this during our last conference call.

Here are a few suggested ways forward:
1. Rebase your branch to master (`git rebase --onto <newBaseBranch> <existingBaseBranch> <branchName>`), revert the latest commit (`git revert <commit>`), and then force push your changes (`git push <remote> <branch> --force`).
2. Create a new local branch built off master named the same as this branch, cherry-pick (`git cherry-pick <commit>`) the two commits you want to keep, and then force push your changes. This does pretty much the same thing as option 1, using more granular steps so it is easier to conceptualize, but takes a bit more work.
3. Create a new branch from master, cherry-pick the two commits, and open a new PR using your new branch. This is the quick-and-dirty option.

If you go with options 1 or 2, I'd suggest creating a local copy of this branch as a backup. If you need any help with this, let me know.

**Comment by dehoni** [comment]
Thank you Chef for talking me through...I go with option 3 before I fall over my feet.

**Pull request closed without merging**
