### PR TITLE
Update core.py filepath

### PR DESCRIPTION
**Pull request by beikerta**
Path .sasview/custom_models does not exist, the plugin models are in .sasview/plugin_models.

### CODE REVIEW

**Comment by beikerta** [comment]
I realised that you can't combine plugin models using core.load_model_info("custom.mymodelname"). This might be a bug - I hope this fix solves the problem. Is there anything I have overseen?

**Comment by butlerpd** [comment]
@pkienzle - can you check this? I thought there were other GUI reasons that custom models are not allowed to be combined at the moment but cannot remember. Was there a change in the folder name going to 5.0.3 that did not get picked up here?

**Comment by pkienzle** [comment]
SasView is storing plugin models in `~/.sasview/plugin_models`, as defined by `sas.sascalc.fit.models.find_plugins_dir()`. This patch is setting `~/.sasmodels/plugin_models`, which won't help since it is not `~/.sasview/plugin_models`.
 
Nominally, sasmodels does not know that sasview exists so it should not be defaulting its paths to the `~/.sasview` directory. Instead, sasview should be setting SAS_MODELPATH to the appropriate directory on startup. This should be done along with the other sasmodels settings in `sas.qtgui.MainWindow.run_sasview` using something like:
```python
    os.environ["SAS_MODELPATH"] = models.find_plugins_dir()
```

Thinking ahead to batch fitting from script these setting should work even if the GUI is not running so they should be moved outside of `sas.qtgui.MainWindow`, but that is a separate issue.

**Comment by butlerpd** [comment]
So this patch somehow suggests the right thing but did not code what it said.  On the other hand, the current code is apparently incorrect.  @pkienzle comment above that the path should be set is fine but the code is run when that is NOT set.  So the correct answer is probably that the whole if statement should be replaced with an error logging message (i.e. if SAS_MODELPATH is ="")  if @beikerta has moved on we need to close the PR and generate a ticket to cover the issue.

**Comment by butlerpd** [comment]
check email of why there is a problem.  otherwise kill PR and add ticket about how to handle default when sas models path is not defined.  @RichardHeenan has seen some strange issues possibly related. Heller says not a problem from sasmodels alone.... @krzywon says error seen in jenkins build.

**Comment by RichardHeenan** [comment]
The email on 18th Sept from Alexandra Biekert was simply the git post above, including:

 I realised that you can't combine plugin models using core.load_model_info("custom.mymodelname")

So the initial issue here presumably relates to an attempt to add or multiply plugin models to make a new plugin, [for which there must be some related tickets elsewhere?].

**Comment by butlerpd** [comment]
as discussed at the fortnightly call the issue raised by this PR and subsequent discussion has been moved to a new issue #433.  The PR can now be closed.

**Pull request closed without merging**
