### PR TITLE
Fixes #1006

### PR DESCRIPTION
**Pull request by gonzalezma**
I reopened the ticket because the plot of the SLD profile was not working when an S(Q) was used. Hopefully, this will close the ticket. I needed to add the **kwargs argument to the profile function in the models to be able to handle the extra volfraction parameter used by the S(Q). Don't know if there could be a better solution.

### CODE REVIEW

**Comment by pkienzle** [comment]
A cleaner solution is to make a wrapper function for the profile which takes all the parameters of the derived model but extracts just the parameters for the form factor model.  It can then call the form factor profile with just those parameters.  

Something like the following in make_product_info [untested]:
```
    if getattr(p_info, 'profile', None) is not None:
        def profile(**kwargs):
            form_factor_args = dict((k, v) for k, v in kwargs.items() if k in p_info.parameters)
            return p_Info.profile(**form_factor_args)
    else:
        profile = None
    ...
    info.profile = profile
    ...
```

This kind of solution is required for mixture model case where all the parameters are renamed, except there the form factor args would be:
```
            form_factor_args = dict((k[len(prefix):], v) for k, v in kwargs.items() if k.startswith(prefix))
```

**Comment by gonzalezma** [comment]
Modified code following Paul K's suggestion. Checked for the 3 models (onion, spherical_sld, and core_multi_shell) that have a profile function. I had to use parameters.kernel_parameters and then split the string to get the base names of the parameters. Is there a better way to get them?

**Comment by pkienzle** [comment]
Couldn't test.  When running current sasview master and selecting spherical_sld, I get the following:
```
Traceback (most recent call last):
  File "/Users/pkienzle/Source/sasview/src/sas/sasgui/perspectives/fitting/fitpage.py", line 1174, in _on_select_model
    self.set_model_param_sizer(self.model)
  File "/Users/pkienzle/Source/sasview/src/sas/sasgui/perspectives/fitting/fitpage.py", line 2860, in set_model_param_sizer
    self._set_fun_box_list(fun_box)
  File "/Users/pkienzle/Source/sasview/src/sas/sasgui/perspectives/fitting/fitpage.py", line 1735, in _set_fun_box_list
    for key, val in list.items():
AttributeError: 'tuple' object has no attribute 'items'
```

Gut feeling is that if you need to rename the parameters to call profile inside the product model, then you will need to rename them when calling profile outside the product model, so profile will be broken when called without a structure factor.

So you are correct, the base name splitting should not be happening in the product model wrapper since it will also be required for the non-product model case.  Don't know where it should be happening though.

**Comment by pkienzle** [comment]
Onion model still works, so I can test.  I updated the code to use p.id rather than p.name which removes the need for splitting.

**Pull request merged**
