### PR TITLE
Ticket776

### PR DESCRIPTION
**Pull request by pkienzle**
Significant model cleanup:
- orientation is now handled by macros, so only need to change it in one place
- use  `square` and `cube` where appropriate rather than pow
- use `M_*PI*`
- use Horner evaluation for polynomials
- use sas library functions (sph_j1c, J1c, sinc)
- remove redundant code; reuse common expressions
- improve accuracy of a number of models

Expand compare function so it can compare different models, or the same model with different parameters.

This does not yet address the main point of ticket776, which is to change the way orientation dispersity is evaluated.

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
There a few failing units tests (they are in fact failing on master as well). 
Do we know why?

FAIL [0.012s]: test_core_shell_cylinder_opencl (__main__.ModelTestCase)
FAIL [0.018s]: test_core_shell_ellipsoid_xt_opencl (__main__.ModelTestCase)
FAIL [0.017s]: test_elliptical_cylinder_opencl (__main__.ModelTestCase)
FAIL [0.027s]: test_parallelepiped_opencl (__main__.ModelTestCase)

**Comment by pkienzle** [comment]
Presumably this is in response to:

    bcc/fcc/sc: slightly slower but more robust calculation of Zq
    https://github.com/SasView/sasmodels/pull/12/commits/0b717c523aa8eedc5d395057a1a2919398332ca7

Unfortunately, I don't remember which particular combination of OpenCL
driver and precision were having problems.

I created ticket #805 to address this.

**Comment by pkienzle** [comment]
Not a particularly useful change (N_POINTS_76 is no more or less
informative than 76), but if you insist then do the same for 20 and 150.

**Comment by pkienzle** [comment]
None of the tests are failing for me.

core_shell_ellipsoid_xt is no longer available.

**Comment by wpotrzebowski** [comment]
Ok, I was calling tests from the wrong place (site packages instead of local sasmodels dir). 
However, when I called them from the right place I still have 3 tests failing:
test_core_shell_cylinder_opencl
test_parallelepiped_opencl
test_raspberry_opencl
This has something to do with my local environment as I don't observe it on other Mac machine and Windows. Need to check it.

**Comment by wpotrzebowski** [comment]
We've been discussing applying adaptive integration at some point. I anticipate It will be easier to adapt the code with  N_POINTS_* than just a number.

**Pull request merged**
